#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoWebsites.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NFU_WEB")]
	public partial class CommunitiesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNFU_COM_Banned_Word(NFU_COM_Banned_Word instance);
    partial void UpdateNFU_COM_Banned_Word(NFU_COM_Banned_Word instance);
    partial void DeleteNFU_COM_Banned_Word(NFU_COM_Banned_Word instance);
    partial void InsertNFU_COM_Comment_Like(NFU_COM_Comment_Like instance);
    partial void UpdateNFU_COM_Comment_Like(NFU_COM_Comment_Like instance);
    partial void DeleteNFU_COM_Comment_Like(NFU_COM_Comment_Like instance);
    partial void InsertNFU_COM_Community(NFU_COM_Community instance);
    partial void UpdateNFU_COM_Community(NFU_COM_Community instance);
    partial void DeleteNFU_COM_Community(NFU_COM_Community instance);
    partial void InsertNFU_COM_Community_Member(NFU_COM_Community_Member instance);
    partial void UpdateNFU_COM_Community_Member(NFU_COM_Community_Member instance);
    partial void DeleteNFU_COM_Community_Member(NFU_COM_Community_Member instance);
    partial void InsertNFU_COM_Deleted_Comment_Type(NFU_COM_Deleted_Comment_Type instance);
    partial void UpdateNFU_COM_Deleted_Comment_Type(NFU_COM_Deleted_Comment_Type instance);
    partial void DeleteNFU_COM_Deleted_Comment_Type(NFU_COM_Deleted_Comment_Type instance);
    partial void InsertNFU_COM_Staff_Name(NFU_COM_Staff_Name instance);
    partial void UpdateNFU_COM_Staff_Name(NFU_COM_Staff_Name instance);
    partial void DeleteNFU_COM_Staff_Name(NFU_COM_Staff_Name instance);
    partial void InsertNFU_COM_User_Tracker(NFU_COM_User_Tracker instance);
    partial void UpdateNFU_COM_User_Tracker(NFU_COM_User_Tracker instance);
    partial void DeleteNFU_COM_User_Tracker(NFU_COM_User_Tracker instance);
    partial void InsertNFU_COM_Comment(NFU_COM_Comment instance);
    partial void UpdateNFU_COM_Comment(NFU_COM_Comment instance);
    partial void DeleteNFU_COM_Comment(NFU_COM_Comment instance);
    partial void InsertNFU_COM_Mod_User(NFU_COM_Mod_User instance);
    partial void UpdateNFU_COM_Mod_User(NFU_COM_Mod_User instance);
    partial void DeleteNFU_COM_Mod_User(NFU_COM_Mod_User instance);
    #endregion
		
		public CommunitiesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CommunitiesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CommunitiesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CommunitiesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NFU_COM_Banned_Word> NFU_COM_Banned_Words
		{
			get
			{
				return this.GetTable<NFU_COM_Banned_Word>();
			}
		}
		
		public System.Data.Linq.Table<NFU_COM_Comment_Like> NFU_COM_Comment_Likes
		{
			get
			{
				return this.GetTable<NFU_COM_Comment_Like>();
			}
		}
		
		public System.Data.Linq.Table<NFU_COM_Community> NFU_COM_Communities
		{
			get
			{
				return this.GetTable<NFU_COM_Community>();
			}
		}
		
		public System.Data.Linq.Table<NFU_COM_Community_Member> NFU_COM_Community_Members
		{
			get
			{
				return this.GetTable<NFU_COM_Community_Member>();
			}
		}
		
		public System.Data.Linq.Table<NFU_COM_Deleted_Comment_Type> NFU_COM_Deleted_Comment_Types
		{
			get
			{
				return this.GetTable<NFU_COM_Deleted_Comment_Type>();
			}
		}
		
		public System.Data.Linq.Table<NFU_COM_Staff_Name> NFU_COM_Staff_Names
		{
			get
			{
				return this.GetTable<NFU_COM_Staff_Name>();
			}
		}
		
		public System.Data.Linq.Table<NFU_COM_User_Tracker> NFU_COM_User_Trackers
		{
			get
			{
				return this.GetTable<NFU_COM_User_Tracker>();
			}
		}
		
		public System.Data.Linq.Table<NFU_COM_Comment> NFU_COM_Comments
		{
			get
			{
				return this.GetTable<NFU_COM_Comment>();
			}
		}
		
		public System.Data.Linq.Table<NFU_COM_Mod_User> NFU_COM_Mod_Users
		{
			get
			{
				return this.GetTable<NFU_COM_Mod_User>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="NFU_COM.NFU_COM_Get_Community_Ids_By_Member")]
		public ISingleResult<NFU_COM_Get_Community_Ids_By_MemberResult> NFU_COM_Get_Community_Ids_By_Member([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string member_name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), member_name);
			return ((ISingleResult<NFU_COM_Get_Community_Ids_By_MemberResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="NFU_COM.NFU_COM_Get_MemberNumbers_By_CommunityId")]
		public ISingleResult<NFU_COM_Get_MemberNumbers_By_CommunityIdResult> NFU_COM_Get_MemberNumbers_By_CommunityId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> community_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), community_id);
			return ((ISingleResult<NFU_COM_Get_MemberNumbers_By_CommunityIdResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="NFU_COM.NFU_COM_Banned_Words")]
	public partial class NFU_COM_Banned_Word : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _word;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnwordChanging(string value);
    partial void OnwordChanged();
    #endregion
		
		public NFU_COM_Banned_Word()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_word", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string word
		{
			get
			{
				return this._word;
			}
			set
			{
				if ((this._word != value))
				{
					this.OnwordChanging(value);
					this.SendPropertyChanging();
					this._word = value;
					this.SendPropertyChanged("word");
					this.OnwordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="NFU_COM.NFU_COM_Comment_Like")]
	public partial class NFU_COM_Comment_Like : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _membership_number;
		
		private int _comment_id;
		
		private bool _deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onmembership_numberChanging(string value);
    partial void Onmembership_numberChanged();
    partial void Oncomment_idChanging(int value);
    partial void Oncomment_idChanged();
    partial void OndeletedChanging(bool value);
    partial void OndeletedChanged();
    #endregion
		
		public NFU_COM_Comment_Like()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_membership_number", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string membership_number
		{
			get
			{
				return this._membership_number;
			}
			set
			{
				if ((this._membership_number != value))
				{
					this.Onmembership_numberChanging(value);
					this.SendPropertyChanging();
					this._membership_number = value;
					this.SendPropertyChanged("membership_number");
					this.Onmembership_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment_id", DbType="Int NOT NULL")]
		public int comment_id
		{
			get
			{
				return this._comment_id;
			}
			set
			{
				if ((this._comment_id != value))
				{
					this.Oncomment_idChanging(value);
					this.SendPropertyChanging();
					this._comment_id = value;
					this.SendPropertyChanged("comment_id");
					this.Oncomment_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit NOT NULL")]
		public bool deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="NFU_COM.NFU_COM_Communities")]
	public partial class NFU_COM_Community : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private bool _deleted;
		
		private EntitySet<NFU_COM_Community_Member> _NFU_COM_Community_Members;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndeletedChanging(bool value);
    partial void OndeletedChanged();
    #endregion
		
		public NFU_COM_Community()
		{
			this._NFU_COM_Community_Members = new EntitySet<NFU_COM_Community_Member>(new Action<NFU_COM_Community_Member>(this.attach_NFU_COM_Community_Members), new Action<NFU_COM_Community_Member>(this.detach_NFU_COM_Community_Members));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit NOT NULL")]
		public bool deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NFU_COM_Community_NFU_COM_Community_Member", Storage="_NFU_COM_Community_Members", ThisKey="id", OtherKey="community_id")]
		public EntitySet<NFU_COM_Community_Member> NFU_COM_Community_Members
		{
			get
			{
				return this._NFU_COM_Community_Members;
			}
			set
			{
				this._NFU_COM_Community_Members.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NFU_COM_Community_Members(NFU_COM_Community_Member entity)
		{
			this.SendPropertyChanging();
			entity.NFU_COM_Community = this;
		}
		
		private void detach_NFU_COM_Community_Members(NFU_COM_Community_Member entity)
		{
			this.SendPropertyChanging();
			entity.NFU_COM_Community = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="NFU_COM.NFU_COM_Community_Members")]
	public partial class NFU_COM_Community_Member : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _membership_number;
		
		private int _community_id;
		
		private bool _deleted;
		
		private System.Nullable<System.DateTime> _date_deleted;
		
		private System.Nullable<int> _deleted_by_mod_id;
		
		private System.DateTime _data_added;
		
		private System.Nullable<System.DateTime> _date_left;
		
		private EntityRef<NFU_COM_Community> _NFU_COM_Community;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onmembership_numberChanging(string value);
    partial void Onmembership_numberChanged();
    partial void Oncommunity_idChanging(int value);
    partial void Oncommunity_idChanged();
    partial void OndeletedChanging(bool value);
    partial void OndeletedChanged();
    partial void Ondate_deletedChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_deletedChanged();
    partial void Ondeleted_by_mod_idChanging(System.Nullable<int> value);
    partial void Ondeleted_by_mod_idChanged();
    partial void Ondata_addedChanging(System.DateTime value);
    partial void Ondata_addedChanged();
    partial void Ondate_leftChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_leftChanged();
    #endregion
		
		public NFU_COM_Community_Member()
		{
			this._NFU_COM_Community = default(EntityRef<NFU_COM_Community>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_membership_number", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string membership_number
		{
			get
			{
				return this._membership_number;
			}
			set
			{
				if ((this._membership_number != value))
				{
					this.Onmembership_numberChanging(value);
					this.SendPropertyChanging();
					this._membership_number = value;
					this.SendPropertyChanged("membership_number");
					this.Onmembership_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_community_id", DbType="Int NOT NULL")]
		public int community_id
		{
			get
			{
				return this._community_id;
			}
			set
			{
				if ((this._community_id != value))
				{
					if (this._NFU_COM_Community.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncommunity_idChanging(value);
					this.SendPropertyChanging();
					this._community_id = value;
					this.SendPropertyChanged("community_id");
					this.Oncommunity_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit NOT NULL")]
		public bool deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_deleted", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_deleted
		{
			get
			{
				return this._date_deleted;
			}
			set
			{
				if ((this._date_deleted != value))
				{
					this.Ondate_deletedChanging(value);
					this.SendPropertyChanging();
					this._date_deleted = value;
					this.SendPropertyChanged("date_deleted");
					this.Ondate_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted_by_mod_id", DbType="Int")]
		public System.Nullable<int> deleted_by_mod_id
		{
			get
			{
				return this._deleted_by_mod_id;
			}
			set
			{
				if ((this._deleted_by_mod_id != value))
				{
					this.Ondeleted_by_mod_idChanging(value);
					this.SendPropertyChanging();
					this._deleted_by_mod_id = value;
					this.SendPropertyChanged("deleted_by_mod_id");
					this.Ondeleted_by_mod_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_added", DbType="DateTime NOT NULL")]
		public System.DateTime data_added
		{
			get
			{
				return this._data_added;
			}
			set
			{
				if ((this._data_added != value))
				{
					this.Ondata_addedChanging(value);
					this.SendPropertyChanging();
					this._data_added = value;
					this.SendPropertyChanged("data_added");
					this.Ondata_addedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_left", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_left
		{
			get
			{
				return this._date_left;
			}
			set
			{
				if ((this._date_left != value))
				{
					this.Ondate_leftChanging(value);
					this.SendPropertyChanging();
					this._date_left = value;
					this.SendPropertyChanged("date_left");
					this.Ondate_leftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NFU_COM_Community_NFU_COM_Community_Member", Storage="_NFU_COM_Community", ThisKey="community_id", OtherKey="id", IsForeignKey=true)]
		public NFU_COM_Community NFU_COM_Community
		{
			get
			{
				return this._NFU_COM_Community.Entity;
			}
			set
			{
				NFU_COM_Community previousValue = this._NFU_COM_Community.Entity;
				if (((previousValue != value) 
							|| (this._NFU_COM_Community.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NFU_COM_Community.Entity = null;
						previousValue.NFU_COM_Community_Members.Remove(this);
					}
					this._NFU_COM_Community.Entity = value;
					if ((value != null))
					{
						value.NFU_COM_Community_Members.Add(this);
						this._community_id = value.id;
					}
					else
					{
						this._community_id = default(int);
					}
					this.SendPropertyChanged("NFU_COM_Community");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="NFU_COM.NFU_COM_Deleted_Comment_Type")]
	public partial class NFU_COM_Deleted_Comment_Type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ComName;
		
		private EntitySet<NFU_COM_Comment> _NFU_COM_Comments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnComNameChanging(string value);
    partial void OnComNameChanged();
    #endregion
		
		public NFU_COM_Deleted_Comment_Type()
		{
			this._NFU_COM_Comments = new EntitySet<NFU_COM_Comment>(new Action<NFU_COM_Comment>(this.attach_NFU_COM_Comments), new Action<NFU_COM_Comment>(this.detach_NFU_COM_Comments));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComName", DbType="NVarChar(50)")]
		public string ComName
		{
			get
			{
				return this._ComName;
			}
			set
			{
				if ((this._ComName != value))
				{
					this.OnComNameChanging(value);
					this.SendPropertyChanging();
					this._ComName = value;
					this.SendPropertyChanged("ComName");
					this.OnComNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NFU_COM_Deleted_Comment_Type_NFU_COM_Comment", Storage="_NFU_COM_Comments", ThisKey="Id", OtherKey="deleted_type_id")]
		public EntitySet<NFU_COM_Comment> NFU_COM_Comments
		{
			get
			{
				return this._NFU_COM_Comments;
			}
			set
			{
				this._NFU_COM_Comments.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NFU_COM_Comments(NFU_COM_Comment entity)
		{
			this.SendPropertyChanging();
			entity.NFU_COM_Deleted_Comment_Type = this;
		}
		
		private void detach_NFU_COM_Comments(NFU_COM_Comment entity)
		{
			this.SendPropertyChanging();
			entity.NFU_COM_Deleted_Comment_Type = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="NFU_COM.NFU_COM_Staff_Names")]
	public partial class NFU_COM_Staff_Name : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public NFU_COM_Staff_Name()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="NFU_COM.NFU_COM_User_Tracker")]
	public partial class NFU_COM_User_Tracker : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _community_member_id;
		
		private System.DateTime _member_timestamp;
		
		private System.Nullable<bool> _joined_community;
		
		private System.Nullable<bool> _left_community;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncommunity_member_idChanging(int value);
    partial void Oncommunity_member_idChanged();
    partial void Onmember_timestampChanging(System.DateTime value);
    partial void Onmember_timestampChanged();
    partial void Onjoined_communityChanging(System.Nullable<bool> value);
    partial void Onjoined_communityChanged();
    partial void Onleft_communityChanging(System.Nullable<bool> value);
    partial void Onleft_communityChanged();
    #endregion
		
		public NFU_COM_User_Tracker()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_community_member_id", DbType="Int NOT NULL")]
		public int community_member_id
		{
			get
			{
				return this._community_member_id;
			}
			set
			{
				if ((this._community_member_id != value))
				{
					this.Oncommunity_member_idChanging(value);
					this.SendPropertyChanging();
					this._community_member_id = value;
					this.SendPropertyChanged("community_member_id");
					this.Oncommunity_member_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_member_timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime member_timestamp
		{
			get
			{
				return this._member_timestamp;
			}
			set
			{
				if ((this._member_timestamp != value))
				{
					this.Onmember_timestampChanging(value);
					this.SendPropertyChanging();
					this._member_timestamp = value;
					this.SendPropertyChanged("member_timestamp");
					this.Onmember_timestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_joined_community", DbType="Bit")]
		public System.Nullable<bool> joined_community
		{
			get
			{
				return this._joined_community;
			}
			set
			{
				if ((this._joined_community != value))
				{
					this.Onjoined_communityChanging(value);
					this.SendPropertyChanging();
					this._joined_community = value;
					this.SendPropertyChanged("joined_community");
					this.Onjoined_communityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_left_community", DbType="Bit")]
		public System.Nullable<bool> left_community
		{
			get
			{
				return this._left_community;
			}
			set
			{
				if ((this._left_community != value))
				{
					this.Onleft_communityChanging(value);
					this.SendPropertyChanging();
					this._left_community = value;
					this.SendPropertyChanged("left_community");
					this.Onleft_communityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="NFU_COM.NFU_COM_Comments")]
	public partial class NFU_COM_Comment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _comment;
		
		private string _membership_number;
		
		private string _member_name;
		
		private System.Nullable<int> _umbraco_page_id;
		
		private int _community_id;
		
		private System.DateTime _date_added;
		
		private System.Nullable<int> _parent_community_id;
		
		private bool _flagged_for_admin;
		
		private bool _deleted;
		
		private int _deleted_by;
		
		private System.Nullable<System.DateTime> _deleted_date;
		
		private System.Nullable<int> _moderated_by;
		
		private System.Nullable<System.DateTime> _moderated_on;
		
		private string _moderator_comments;
		
		private bool _seen_by_mod;
		
		private bool _user_left_community;
		
		private System.Nullable<int> _deleted_type_id;
		
		private string _send_to_moderator_email;
		
		private string _send_to_moderator_email_note;
		
		private System.Nullable<System.DateTime> _send_to_moderated_email_on;
		
		private EntityRef<NFU_COM_Deleted_Comment_Type> _NFU_COM_Deleted_Comment_Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void Onmembership_numberChanging(string value);
    partial void Onmembership_numberChanged();
    partial void Onmember_nameChanging(string value);
    partial void Onmember_nameChanged();
    partial void Onumbraco_page_idChanging(System.Nullable<int> value);
    partial void Onumbraco_page_idChanged();
    partial void Oncommunity_idChanging(int value);
    partial void Oncommunity_idChanged();
    partial void Ondate_addedChanging(System.DateTime value);
    partial void Ondate_addedChanged();
    partial void Onparent_community_idChanging(System.Nullable<int> value);
    partial void Onparent_community_idChanged();
    partial void Onflagged_for_adminChanging(bool value);
    partial void Onflagged_for_adminChanged();
    partial void OndeletedChanging(bool value);
    partial void OndeletedChanged();
    partial void Ondeleted_byChanging(int value);
    partial void Ondeleted_byChanged();
    partial void Ondeleted_dateChanging(System.Nullable<System.DateTime> value);
    partial void Ondeleted_dateChanged();
    partial void Onmoderated_byChanging(System.Nullable<int> value);
    partial void Onmoderated_byChanged();
    partial void Onmoderated_onChanging(System.Nullable<System.DateTime> value);
    partial void Onmoderated_onChanged();
    partial void Onmoderator_commentsChanging(string value);
    partial void Onmoderator_commentsChanged();
    partial void Onseen_by_modChanging(bool value);
    partial void Onseen_by_modChanged();
    partial void Onuser_left_communityChanging(bool value);
    partial void Onuser_left_communityChanged();
    partial void Ondeleted_type_idChanging(System.Nullable<int> value);
    partial void Ondeleted_type_idChanged();
    partial void Onsend_to_moderator_emailChanging(string value);
    partial void Onsend_to_moderator_emailChanged();
    partial void Onsend_to_moderator_email_noteChanging(string value);
    partial void Onsend_to_moderator_email_noteChanged();
    partial void Onsend_to_moderated_email_onChanging(System.Nullable<System.DateTime> value);
    partial void Onsend_to_moderated_email_onChanged();
    #endregion
		
		public NFU_COM_Comment()
		{
			this._NFU_COM_Deleted_Comment_Type = default(EntityRef<NFU_COM_Deleted_Comment_Type>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_membership_number", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string membership_number
		{
			get
			{
				return this._membership_number;
			}
			set
			{
				if ((this._membership_number != value))
				{
					this.Onmembership_numberChanging(value);
					this.SendPropertyChanging();
					this._membership_number = value;
					this.SendPropertyChanged("membership_number");
					this.Onmembership_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_member_name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string member_name
		{
			get
			{
				return this._member_name;
			}
			set
			{
				if ((this._member_name != value))
				{
					this.Onmember_nameChanging(value);
					this.SendPropertyChanging();
					this._member_name = value;
					this.SendPropertyChanged("member_name");
					this.Onmember_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_umbraco_page_id", DbType="Int")]
		public System.Nullable<int> umbraco_page_id
		{
			get
			{
				return this._umbraco_page_id;
			}
			set
			{
				if ((this._umbraco_page_id != value))
				{
					this.Onumbraco_page_idChanging(value);
					this.SendPropertyChanging();
					this._umbraco_page_id = value;
					this.SendPropertyChanged("umbraco_page_id");
					this.Onumbraco_page_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_community_id", DbType="Int NOT NULL")]
		public int community_id
		{
			get
			{
				return this._community_id;
			}
			set
			{
				if ((this._community_id != value))
				{
					this.Oncommunity_idChanging(value);
					this.SendPropertyChanging();
					this._community_id = value;
					this.SendPropertyChanged("community_id");
					this.Oncommunity_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_added", DbType="DateTime NOT NULL")]
		public System.DateTime date_added
		{
			get
			{
				return this._date_added;
			}
			set
			{
				if ((this._date_added != value))
				{
					this.Ondate_addedChanging(value);
					this.SendPropertyChanging();
					this._date_added = value;
					this.SendPropertyChanged("date_added");
					this.Ondate_addedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_community_id", DbType="Int")]
		public System.Nullable<int> parent_community_id
		{
			get
			{
				return this._parent_community_id;
			}
			set
			{
				if ((this._parent_community_id != value))
				{
					this.Onparent_community_idChanging(value);
					this.SendPropertyChanging();
					this._parent_community_id = value;
					this.SendPropertyChanged("parent_community_id");
					this.Onparent_community_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flagged_for_admin", DbType="Bit NOT NULL")]
		public bool flagged_for_admin
		{
			get
			{
				return this._flagged_for_admin;
			}
			set
			{
				if ((this._flagged_for_admin != value))
				{
					this.Onflagged_for_adminChanging(value);
					this.SendPropertyChanging();
					this._flagged_for_admin = value;
					this.SendPropertyChanged("flagged_for_admin");
					this.Onflagged_for_adminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit NOT NULL")]
		public bool deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted_by", DbType="Int NOT NULL")]
		public int deleted_by
		{
			get
			{
				return this._deleted_by;
			}
			set
			{
				if ((this._deleted_by != value))
				{
					this.Ondeleted_byChanging(value);
					this.SendPropertyChanging();
					this._deleted_by = value;
					this.SendPropertyChanged("deleted_by");
					this.Ondeleted_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> deleted_date
		{
			get
			{
				return this._deleted_date;
			}
			set
			{
				if ((this._deleted_date != value))
				{
					this.Ondeleted_dateChanging(value);
					this.SendPropertyChanging();
					this._deleted_date = value;
					this.SendPropertyChanged("deleted_date");
					this.Ondeleted_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moderated_by", DbType="Int")]
		public System.Nullable<int> moderated_by
		{
			get
			{
				return this._moderated_by;
			}
			set
			{
				if ((this._moderated_by != value))
				{
					this.Onmoderated_byChanging(value);
					this.SendPropertyChanging();
					this._moderated_by = value;
					this.SendPropertyChanged("moderated_by");
					this.Onmoderated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moderated_on", DbType="DateTime")]
		public System.Nullable<System.DateTime> moderated_on
		{
			get
			{
				return this._moderated_on;
			}
			set
			{
				if ((this._moderated_on != value))
				{
					this.Onmoderated_onChanging(value);
					this.SendPropertyChanging();
					this._moderated_on = value;
					this.SendPropertyChanged("moderated_on");
					this.Onmoderated_onChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moderator_comments", DbType="NVarChar(MAX)")]
		public string moderator_comments
		{
			get
			{
				return this._moderator_comments;
			}
			set
			{
				if ((this._moderator_comments != value))
				{
					this.Onmoderator_commentsChanging(value);
					this.SendPropertyChanging();
					this._moderator_comments = value;
					this.SendPropertyChanged("moderator_comments");
					this.Onmoderator_commentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seen_by_mod", DbType="Bit NOT NULL")]
		public bool seen_by_mod
		{
			get
			{
				return this._seen_by_mod;
			}
			set
			{
				if ((this._seen_by_mod != value))
				{
					this.Onseen_by_modChanging(value);
					this.SendPropertyChanging();
					this._seen_by_mod = value;
					this.SendPropertyChanged("seen_by_mod");
					this.Onseen_by_modChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_left_community", DbType="Bit NOT NULL")]
		public bool user_left_community
		{
			get
			{
				return this._user_left_community;
			}
			set
			{
				if ((this._user_left_community != value))
				{
					this.Onuser_left_communityChanging(value);
					this.SendPropertyChanging();
					this._user_left_community = value;
					this.SendPropertyChanged("user_left_community");
					this.Onuser_left_communityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted_type_id", DbType="Int")]
		public System.Nullable<int> deleted_type_id
		{
			get
			{
				return this._deleted_type_id;
			}
			set
			{
				if ((this._deleted_type_id != value))
				{
					if (this._NFU_COM_Deleted_Comment_Type.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondeleted_type_idChanging(value);
					this.SendPropertyChanging();
					this._deleted_type_id = value;
					this.SendPropertyChanged("deleted_type_id");
					this.Ondeleted_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_send_to_moderator_email", DbType="NVarChar(250)")]
		public string send_to_moderator_email
		{
			get
			{
				return this._send_to_moderator_email;
			}
			set
			{
				if ((this._send_to_moderator_email != value))
				{
					this.Onsend_to_moderator_emailChanging(value);
					this.SendPropertyChanging();
					this._send_to_moderator_email = value;
					this.SendPropertyChanged("send_to_moderator_email");
					this.Onsend_to_moderator_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_send_to_moderator_email_note", DbType="NVarChar(MAX)")]
		public string send_to_moderator_email_note
		{
			get
			{
				return this._send_to_moderator_email_note;
			}
			set
			{
				if ((this._send_to_moderator_email_note != value))
				{
					this.Onsend_to_moderator_email_noteChanging(value);
					this.SendPropertyChanging();
					this._send_to_moderator_email_note = value;
					this.SendPropertyChanged("send_to_moderator_email_note");
					this.Onsend_to_moderator_email_noteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_send_to_moderated_email_on", DbType="DateTime")]
		public System.Nullable<System.DateTime> send_to_moderated_email_on
		{
			get
			{
				return this._send_to_moderated_email_on;
			}
			set
			{
				if ((this._send_to_moderated_email_on != value))
				{
					this.Onsend_to_moderated_email_onChanging(value);
					this.SendPropertyChanging();
					this._send_to_moderated_email_on = value;
					this.SendPropertyChanged("send_to_moderated_email_on");
					this.Onsend_to_moderated_email_onChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NFU_COM_Deleted_Comment_Type_NFU_COM_Comment", Storage="_NFU_COM_Deleted_Comment_Type", ThisKey="deleted_type_id", OtherKey="Id", IsForeignKey=true)]
		public NFU_COM_Deleted_Comment_Type NFU_COM_Deleted_Comment_Type
		{
			get
			{
				return this._NFU_COM_Deleted_Comment_Type.Entity;
			}
			set
			{
				NFU_COM_Deleted_Comment_Type previousValue = this._NFU_COM_Deleted_Comment_Type.Entity;
				if (((previousValue != value) 
							|| (this._NFU_COM_Deleted_Comment_Type.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NFU_COM_Deleted_Comment_Type.Entity = null;
						previousValue.NFU_COM_Comments.Remove(this);
					}
					this._NFU_COM_Deleted_Comment_Type.Entity = value;
					if ((value != null))
					{
						value.NFU_COM_Comments.Add(this);
						this._deleted_type_id = value.Id;
					}
					else
					{
						this._deleted_type_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("NFU_COM_Deleted_Comment_Type");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="NFU_COM.NFU_COM_Mod_Users")]
	public partial class NFU_COM_Mod_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _email;
		
		private string _pw;
		
		private System.DateTime _last_logged_in;
		
		private bool _deleted;
		
		private string _name;
		
		private string _membership_number;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpwChanging(string value);
    partial void OnpwChanged();
    partial void Onlast_logged_inChanging(System.DateTime value);
    partial void Onlast_logged_inChanged();
    partial void OndeletedChanging(bool value);
    partial void OndeletedChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onmembership_numberChanging(string value);
    partial void Onmembership_numberChanged();
    #endregion
		
		public NFU_COM_Mod_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pw", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string pw
		{
			get
			{
				return this._pw;
			}
			set
			{
				if ((this._pw != value))
				{
					this.OnpwChanging(value);
					this.SendPropertyChanging();
					this._pw = value;
					this.SendPropertyChanged("pw");
					this.OnpwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_logged_in", DbType="DateTime NOT NULL")]
		public System.DateTime last_logged_in
		{
			get
			{
				return this._last_logged_in;
			}
			set
			{
				if ((this._last_logged_in != value))
				{
					this.Onlast_logged_inChanging(value);
					this.SendPropertyChanging();
					this._last_logged_in = value;
					this.SendPropertyChanged("last_logged_in");
					this.Onlast_logged_inChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit NOT NULL")]
		public bool deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(250)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_membership_number", DbType="NVarChar(10)")]
		public string membership_number
		{
			get
			{
				return this._membership_number;
			}
			set
			{
				if ((this._membership_number != value))
				{
					this.Onmembership_numberChanging(value);
					this.SendPropertyChanging();
					this._membership_number = value;
					this.SendPropertyChanged("membership_number");
					this.Onmembership_numberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class NFU_COM_Get_Community_Ids_By_MemberResult
	{
		
		private int _community_id;
		
		public NFU_COM_Get_Community_Ids_By_MemberResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_community_id", DbType="Int NOT NULL")]
		public int community_id
		{
			get
			{
				return this._community_id;
			}
			set
			{
				if ((this._community_id != value))
				{
					this._community_id = value;
				}
			}
		}
	}
	
	public partial class NFU_COM_Get_MemberNumbers_By_CommunityIdResult
	{
		
		private System.Nullable<int> _NumberOfMembers;
		
		public NFU_COM_Get_MemberNumbers_By_CommunityIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfMembers", DbType="Int")]
		public System.Nullable<int> NumberOfMembers
		{
			get
			{
				return this._NumberOfMembers;
			}
			set
			{
				if ((this._NumberOfMembers != value))
				{
					this._NumberOfMembers = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
