#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoWebsites.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CRM_TEST")]
	public partial class CrmSprocsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public CrmSprocsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CRM_TESTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CrmSprocsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CrmSprocsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CrmSprocsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CrmSprocsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CUST_NFU_MOB_APP_MEETREG_GetMeetingAttendees")]
		public ISingleResult<CUST_NFU_MOB_APP_MEETREG_GetMeetingAttendeesResult> CUST_NFU_MOB_APP_MEETREG_GetMeetingAttendees([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CUST_NFU_MARKETING_Code", DbType="NVarChar(50)")] string cUST_NFU_MARKETING_Code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cUST_NFU_MARKETING_Code);
			return ((ISingleResult<CUST_NFU_MOB_APP_MEETREG_GetMeetingAttendeesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CUST_NFU_NETZERO_Map_Data")]
		public ISingleResult<CUST_NFU_NETZERO_Map_DataResult> CUST_NFU_NETZERO_Map_Data()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CUST_NFU_NETZERO_Map_DataResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NFU_WEB_Contact_GUID_Lookup")]
		public ISingleResult<NFU_WEB_Contact_GUID_LookupResult> NFU_WEB_Contact_GUID_Lookup([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> uID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uID);
			return ((ISingleResult<NFU_WEB_Contact_GUID_LookupResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CUST_NFU_Get_Sug_Board")]
		public ISingleResult<CUST_NFU_Get_Sug_BoardResult> CUST_NFU_Get_Sug_Board([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADDRESS_PostCode", DbType="NVarChar(50)")] string aDDRESS_PostCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aDDRESS_PostCode);
			return ((ISingleResult<CUST_NFU_Get_Sug_BoardResult>)(result.ReturnValue));
		}
	}
	
	public partial class CUST_NFU_MOB_APP_MEETREG_GetMeetingAttendeesResult
	{
		
		private string _CONTACT_Id;
		
		private string _FullName;
		
		private string _NoAttending;
		
		private string _AttendeeName;
		
		private string _TypeofBusiness;
		
		private string _DietaryRequirements;
		
		private System.Nullable<System.DateTime> _RegistrationDate;
		
		private System.Nullable<bool> _AttendedMeeting;
		
		private System.Nullable<bool> _Removed;
		
		private int _CUST_NFU_CONTACT_MARKETING_INFORMATION_Id;
		
		private System.Nullable<System.Guid> _UniqueId;
		
		public CUST_NFU_MOB_APP_MEETREG_GetMeetingAttendeesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT_Id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CONTACT_Id
		{
			get
			{
				return this._CONTACT_Id;
			}
			set
			{
				if ((this._CONTACT_Id != value))
				{
					this._CONTACT_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(255)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoAttending", DbType="NVarChar(50)")]
		public string NoAttending
		{
			get
			{
				return this._NoAttending;
			}
			set
			{
				if ((this._NoAttending != value))
				{
					this._NoAttending = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendeeName", DbType="NVarChar(MAX)")]
		public string AttendeeName
		{
			get
			{
				return this._AttendeeName;
			}
			set
			{
				if ((this._AttendeeName != value))
				{
					this._AttendeeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeofBusiness", DbType="NVarChar(MAX)")]
		public string TypeofBusiness
		{
			get
			{
				return this._TypeofBusiness;
			}
			set
			{
				if ((this._TypeofBusiness != value))
				{
					this._TypeofBusiness = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DietaryRequirements", DbType="NVarChar(MAX)")]
		public string DietaryRequirements
		{
			get
			{
				return this._DietaryRequirements;
			}
			set
			{
				if ((this._DietaryRequirements != value))
				{
					this._DietaryRequirements = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistrationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> RegistrationDate
		{
			get
			{
				return this._RegistrationDate;
			}
			set
			{
				if ((this._RegistrationDate != value))
				{
					this._RegistrationDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendedMeeting", DbType="Bit")]
		public System.Nullable<bool> AttendedMeeting
		{
			get
			{
				return this._AttendedMeeting;
			}
			set
			{
				if ((this._AttendedMeeting != value))
				{
					this._AttendedMeeting = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Removed", DbType="Bit")]
		public System.Nullable<bool> Removed
		{
			get
			{
				return this._Removed;
			}
			set
			{
				if ((this._Removed != value))
				{
					this._Removed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_NFU_CONTACT_MARKETING_INFORMATION_Id", DbType="Int NOT NULL")]
		public int CUST_NFU_CONTACT_MARKETING_INFORMATION_Id
		{
			get
			{
				return this._CUST_NFU_CONTACT_MARKETING_INFORMATION_Id;
			}
			set
			{
				if ((this._CUST_NFU_CONTACT_MARKETING_INFORMATION_Id != value))
				{
					this._CUST_NFU_CONTACT_MARKETING_INFORMATION_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UniqueId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UniqueId
		{
			get
			{
				return this._UniqueId;
			}
			set
			{
				if ((this._UniqueId != value))
				{
					this._UniqueId = value;
				}
			}
		}
	}
	
	public partial class CUST_NFU_NETZERO_Map_DataResult
	{
		
		private string _CONTACT_Id;
		
		private string _CUST_NFU_MARKETING_CATEGORY_Code;
		
		private string _CUST_NFU_MARKETING_CATEGORY_Desc;
		
		private string _CUST_NFU_MARKETING_Code;
		
		private string _CUST_NFU_MARKETING_Desc;
		
		private string _CUST_NFU_CONTACT_MARKETING_INFORMATION_Value;
		
		private decimal _ADDRESS_Longitude;
		
		private decimal _ADDRESS_Latitude;
		
		private string _County;
		
		public CUST_NFU_NETZERO_Map_DataResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT_Id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CONTACT_Id
		{
			get
			{
				return this._CONTACT_Id;
			}
			set
			{
				if ((this._CONTACT_Id != value))
				{
					this._CONTACT_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_NFU_MARKETING_CATEGORY_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CUST_NFU_MARKETING_CATEGORY_Code
		{
			get
			{
				return this._CUST_NFU_MARKETING_CATEGORY_Code;
			}
			set
			{
				if ((this._CUST_NFU_MARKETING_CATEGORY_Code != value))
				{
					this._CUST_NFU_MARKETING_CATEGORY_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_NFU_MARKETING_CATEGORY_Desc", DbType="NVarChar(50)")]
		public string CUST_NFU_MARKETING_CATEGORY_Desc
		{
			get
			{
				return this._CUST_NFU_MARKETING_CATEGORY_Desc;
			}
			set
			{
				if ((this._CUST_NFU_MARKETING_CATEGORY_Desc != value))
				{
					this._CUST_NFU_MARKETING_CATEGORY_Desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_NFU_MARKETING_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CUST_NFU_MARKETING_Code
		{
			get
			{
				return this._CUST_NFU_MARKETING_Code;
			}
			set
			{
				if ((this._CUST_NFU_MARKETING_Code != value))
				{
					this._CUST_NFU_MARKETING_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_NFU_MARKETING_Desc", DbType="NVarChar(50)")]
		public string CUST_NFU_MARKETING_Desc
		{
			get
			{
				return this._CUST_NFU_MARKETING_Desc;
			}
			set
			{
				if ((this._CUST_NFU_MARKETING_Desc != value))
				{
					this._CUST_NFU_MARKETING_Desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_NFU_CONTACT_MARKETING_INFORMATION_Value", DbType="NVarChar(50)")]
		public string CUST_NFU_CONTACT_MARKETING_INFORMATION_Value
		{
			get
			{
				return this._CUST_NFU_CONTACT_MARKETING_INFORMATION_Value;
			}
			set
			{
				if ((this._CUST_NFU_CONTACT_MARKETING_INFORMATION_Value != value))
				{
					this._CUST_NFU_CONTACT_MARKETING_INFORMATION_Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS_Longitude", DbType="Decimal(9,6) NOT NULL")]
		public decimal ADDRESS_Longitude
		{
			get
			{
				return this._ADDRESS_Longitude;
			}
			set
			{
				if ((this._ADDRESS_Longitude != value))
				{
					this._ADDRESS_Longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS_Latitude", DbType="Decimal(9,6) NOT NULL")]
		public decimal ADDRESS_Latitude
		{
			get
			{
				return this._ADDRESS_Latitude;
			}
			set
			{
				if ((this._ADDRESS_Latitude != value))
				{
					this._ADDRESS_Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="NVarChar(4000)")]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this._County = value;
				}
			}
		}
	}
	
	public partial class NFU_WEB_Contact_GUID_LookupResult
	{
		
		private string _CONTACT_Id;
		
		public NFU_WEB_Contact_GUID_LookupResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT_Id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CONTACT_Id
		{
			get
			{
				return this._CONTACT_Id;
			}
			set
			{
				if ((this._CONTACT_Id != value))
				{
					this._CONTACT_Id = value;
				}
			}
		}
	}
	
	public partial class CUST_NFU_Get_Sug_BoardResult
	{
		
		private string _CONTACT_Id;
		
		private string _CONTACT_PostName;
		
		private string _PrfEmail;
		
		private string _PrfTel;
		
		private string _PrfMobile;
		
		public CUST_NFU_Get_Sug_BoardResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT_Id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CONTACT_Id
		{
			get
			{
				return this._CONTACT_Id;
			}
			set
			{
				if ((this._CONTACT_Id != value))
				{
					this._CONTACT_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT_PostName", DbType="NVarChar(255)")]
		public string CONTACT_PostName
		{
			get
			{
				return this._CONTACT_PostName;
			}
			set
			{
				if ((this._CONTACT_PostName != value))
				{
					this._CONTACT_PostName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrfEmail", DbType="NVarChar(255)")]
		public string PrfEmail
		{
			get
			{
				return this._PrfEmail;
			}
			set
			{
				if ((this._PrfEmail != value))
				{
					this._PrfEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrfTel", DbType="NVarChar(306)")]
		public string PrfTel
		{
			get
			{
				return this._PrfTel;
			}
			set
			{
				if ((this._PrfTel != value))
				{
					this._PrfTel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrfMobile", DbType="NVarChar(4000)")]
		public string PrfMobile
		{
			get
			{
				return this._PrfMobile;
			}
			set
			{
				if ((this._PrfMobile != value))
				{
					this._PrfMobile = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
