#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoWebsites.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NFU_Custom_Website_Data")]
	public partial class CustomWebsiteDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRoadmap_Category(Roadmap_Category instance);
    partial void UpdateRoadmap_Category(Roadmap_Category instance);
    partial void DeleteRoadmap_Category(Roadmap_Category instance);
    partial void InsertRoadmap_Chart(Roadmap_Chart instance);
    partial void UpdateRoadmap_Chart(Roadmap_Chart instance);
    partial void DeleteRoadmap_Chart(Roadmap_Chart instance);
    partial void InsertRoadmap_Entry(Roadmap_Entry instance);
    partial void UpdateRoadmap_Entry(Roadmap_Entry instance);
    partial void DeleteRoadmap_Entry(Roadmap_Entry instance);
    partial void InsertRoadmap_Timeframe(Roadmap_Timeframe instance);
    partial void UpdateRoadmap_Timeframe(Roadmap_Timeframe instance);
    partial void DeleteRoadmap_Timeframe(Roadmap_Timeframe instance);
    partial void InsertRoadmap_Value(Roadmap_Value instance);
    partial void UpdateRoadmap_Value(Roadmap_Value instance);
    partial void DeleteRoadmap_Value(Roadmap_Value instance);
    partial void InsertIpmSuggestion(IpmSuggestion instance);
    partial void UpdateIpmSuggestion(IpmSuggestion instance);
    partial void DeleteIpmSuggestion(IpmSuggestion instance);
        #endregion

        public CustomWebsiteDataDataContext() :
        base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NFU_Custom_Website_DataConnectionString"].ConnectionString, mappingSource)
        {
            OnCreated();
        }

        public CustomWebsiteDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomWebsiteDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomWebsiteDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomWebsiteDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Roadmap_Category> Roadmap_Categories
		{
			get
			{
				return this.GetTable<Roadmap_Category>();
			}
		}
		
		public System.Data.Linq.Table<Roadmap_Chart> Roadmap_Charts
		{
			get
			{
				return this.GetTable<Roadmap_Chart>();
			}
		}
		
		public System.Data.Linq.Table<Roadmap_Entry> Roadmap_Entries
		{
			get
			{
				return this.GetTable<Roadmap_Entry>();
			}
		}
		
		public System.Data.Linq.Table<Roadmap_Timeframe> Roadmap_Timeframes
		{
			get
			{
				return this.GetTable<Roadmap_Timeframe>();
			}
		}
		
		public System.Data.Linq.Table<Roadmap_Value> Roadmap_Values
		{
			get
			{
				return this.GetTable<Roadmap_Value>();
			}
		}
		
		public System.Data.Linq.Table<IpmSuggestion> IpmSuggestions
		{
			get
			{
				return this.GetTable<IpmSuggestion>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectFromIpmOption")]
		public ISingleResult<SelectFromIpmOptionResult> SelectFromIpmOption([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), surveyId);
			return ((ISingleResult<SelectFromIpmOptionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectFromIpmOptionBySubQuestionId")]
		public ISingleResult<SelectFromIpmOptionBySubQuestionIdResult> SelectFromIpmOptionBySubQuestionId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuestionId", DbType="Int")] System.Nullable<int> questionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubQuestionId", DbType="Int")] System.Nullable<int> subQuestionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), surveyId, questionId, subQuestionId);
			return ((ISingleResult<SelectFromIpmOptionBySubQuestionIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectFromIpmQuestion")]
		public ISingleResult<SelectFromIpmQuestionResult> SelectFromIpmQuestion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), surveyId);
			return ((ISingleResult<SelectFromIpmQuestionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectFromIpmQuestionByQuestionId")]
		public ISingleResult<SelectFromIpmQuestionByQuestionIdResult> SelectFromIpmQuestionByQuestionId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuestionNumber", DbType="Int")] System.Nullable<int> questionNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), surveyId, questionNumber);
			return ((ISingleResult<SelectFromIpmQuestionByQuestionIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectFromIpmResult")]
		public ISingleResult<SelectFromIpmResultResult> SelectFromIpmResult([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), surveyId);
			return ((ISingleResult<SelectFromIpmResultResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectFromIpmResultBySubmissionId")]
		public ISingleResult<SelectFromIpmResultBySubmissionIdResult> SelectFromIpmResultBySubmissionId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="Int")] System.Nullable<int> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubmissionId", DbType="Int")] System.Nullable<int> submissionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), surveyId, userId, submissionId);
			return ((ISingleResult<SelectFromIpmResultBySubmissionIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectFromIpmResultByUserId")]
		public ISingleResult<SelectFromIpmResultByUserIdResult> SelectFromIpmResultByUserId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="Int")] System.Nullable<int> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), surveyId, userId);
			return ((ISingleResult<SelectFromIpmResultByUserIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectFromIpmSubquestion")]
		public ISingleResult<SelectFromIpmSubquestionResult> SelectFromIpmSubquestion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), surveyId);
			return ((ISingleResult<SelectFromIpmSubquestionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectFromIpmSubquestionByQuestionId")]
		public ISingleResult<SelectFromIpmSubquestionByQuestionIdResult> SelectFromIpmSubquestionByQuestionId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuestionId", DbType="Int")] System.Nullable<int> questionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), surveyId, questionId);
			return ((ISingleResult<SelectFromIpmSubquestionByQuestionIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectFromIpmSurveyById")]
		public ISingleResult<SelectFromIpmSurveyByIdResult> SelectFromIpmSurveyById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), surveyId);
			return ((ISingleResult<SelectFromIpmSurveyByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectFromIpmUser")]
		public ISingleResult<SelectFromIpmUserResult> SelectFromIpmUser()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SelectFromIpmUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectFromIpmUserById")]
		public ISingleResult<SelectFromIpmUserByIdResult> SelectFromIpmUserById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<SelectFromIpmUserByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertToIpmResult")]
		public int InsertToIpmResult([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="Int")] System.Nullable<int> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubmissionId", DbType="Int")] System.Nullable<int> submissionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OptionText", DbType="NVarChar(200)")] string optionText, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OptionId", DbType="Int")] System.Nullable<int> optionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubQuestionId", DbType="Int")] System.Nullable<int> subQuestionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuestionId", DbType="Int")] System.Nullable<int> questionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Weighting", DbType="NVarChar(10)")] string weighting)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), surveyId, userId, submissionId, optionText, optionId, subQuestionId, questionId, weighting);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertToIpmUser")]
		public ISingleResult<InsertToIpmUserResult> InsertToIpmUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="NVarChar(50)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Surname", DbType="NVarChar(50)")] string surname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailAddress", DbType="NVarChar(50)")] string emailAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company", DbType="NVarChar(50)")] string company, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddressLineOne", DbType="NVarChar(50)")] string addressLineOne, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddressLineTwo", DbType="NVarChar(50)")] string addressLineTwo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddressLineThree", DbType="NVarChar(50)")] string addressLineThree, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Town", DbType="NVarChar(50)")] string town, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="County", DbType="NVarChar(50)")] string county, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostCode", DbType="NVarChar(15)")] string postCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsMember", DbType="Bit")] System.Nullable<bool> isMember, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MembershipNumber", DbType="NVarChar(10)")] string membershipNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateAdded", DbType="DateTime")] System.Nullable<System.DateTime> dateAdded)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), firstName, surname, emailAddress, company, addressLineOne, addressLineTwo, addressLineThree, town, county, postCode, isMember, membershipNumber, dateAdded);
			return ((ISingleResult<InsertToIpmUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateToIpmResult")]
		public int UpdateToIpmResult([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="Int")] System.Nullable<int> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubmissionId", DbType="Int")] System.Nullable<int> submissionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OptionText", DbType="NVarChar(200)")] string optionText, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OptionId", DbType="Int")] System.Nullable<int> optionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubQuestionId", DbType="Int")] System.Nullable<int> subQuestionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuestionId", DbType="Int")] System.Nullable<int> questionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Weighting", DbType="NVarChar(10)")] string weighting)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, surveyId, userId, submissionId, optionText, optionId, subQuestionId, questionId, weighting);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateToIpmUser")]
		public int UpdateToIpmUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="NVarChar(50)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Surname", DbType="NVarChar(50)")] string surname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailAddress", DbType="NVarChar(50)")] string emailAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company", DbType="NVarChar(50)")] string company, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddressLineOne", DbType="NVarChar(50)")] string addressLineOne, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddressLineTwo", DbType="NVarChar(50)")] string addressLineTwo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddressLineThree", DbType="NVarChar(50)")] string addressLineThree, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Town", DbType="NVarChar(50)")] string town, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="County", DbType="NVarChar(50)")] string county, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostCode", DbType="NVarChar(15)")] string postCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsMember", DbType="Bit")] System.Nullable<bool> isMember, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MembershipNumber", DbType="NVarChar(10)")] string membershipNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateAdded", DbType="DateTime")] System.Nullable<System.DateTime> dateAdded)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, firstName, surname, emailAddress, company, addressLineOne, addressLineTwo, addressLineThree, town, county, postCode, isMember, membershipNumber, dateAdded);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PostcodeAnyWhereData_Insert")]
		public int PostcodeAnyWhereData_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Postcode", DbType="NVarChar(50)")] string postcode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Latitude", DbType="Float")] System.Nullable<double> latitude, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> longitude)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), postcode, latitude, longitude);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PostcodeAnyWhereData_CheckForPostcode")]
		public ISingleResult<PostcodeAnyWhereData_CheckForPostcodeResult> PostcodeAnyWhereData_CheckForPostcode([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Postcode", DbType="NVarChar(50)")] string postcode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), postcode);
			return ((ISingleResult<PostcodeAnyWhereData_CheckForPostcodeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PostcodeAnyWhereRequests_Insert")]
		public int PostcodeAnyWhereRequests_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Postcode", DbType="NVarChar(50)")] string postcode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SiteId", DbType="BigInt")] System.Nullable<long> siteId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), postcode, siteId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CUST_NFU_SUG_Get_NgageAsset")]
		public int CUST_NFU_SUG_Get_NgageAsset([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string postCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), postCode);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertToIpmSubmission")]
		public ISingleResult<InsertToIpmSubmissionResult> InsertToIpmSubmission([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="Int")] System.Nullable<int> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsComplete", DbType="Int")] System.Nullable<int> isComplete, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubmissionDate", DbType="DateTime")] System.Nullable<System.DateTime> submissionDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserGuid", DbType="UniqueIdentifier")] System.Nullable<System.Guid> userGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), surveyId, userId, isComplete, submissionDate, userGuid);
			return ((ISingleResult<InsertToIpmSubmissionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectFromIpmSubmission")]
		public ISingleResult<SelectFromIpmSubmissionResult> SelectFromIpmSubmission([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), surveyId);
			return ((ISingleResult<SelectFromIpmSubmissionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectFromIpmSubmissionByUserId")]
		public ISingleResult<SelectFromIpmSubmissionByUserIdResult> SelectFromIpmSubmissionByUserId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="Int")] System.Nullable<int> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), surveyId, userId);
			return ((ISingleResult<SelectFromIpmSubmissionByUserIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectFromIpmSubmissionById")]
		public ISingleResult<SelectFromIpmSubmissionByIdResult> SelectFromIpmSubmissionById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubmissionId", DbType="Int")] System.Nullable<int> submissionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), surveyId, submissionId);
			return ((ISingleResult<SelectFromIpmSubmissionByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectFromIpmSubmissionByStatus")]
		public ISingleResult<SelectFromIpmSubmissionByStatusResult> SelectFromIpmSubmissionByStatus([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsComplete", DbType="Bit")] System.Nullable<bool> isComplete)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), surveyId, isComplete);
			return ((ISingleResult<SelectFromIpmSubmissionByStatusResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateToIpmSubmissionById")]
		public int UpdateToIpmSubmissionById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="Int")] System.Nullable<int> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsComplete", DbType="Int")] System.Nullable<int> isComplete, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubmissionDate", DbType="DateTime")] System.Nullable<System.DateTime> submissionDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserGuid", DbType="UniqueIdentifier")] System.Nullable<System.Guid> userGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, surveyId, userId, isComplete, submissionDate, userGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RemoveFromlpmResult")]
		public int RemoveFromlpmResult([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roadmap_Categories")]
	public partial class Roadmap_Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _ChartId;
		
		private string _Title;
		
		private System.Nullable<int> _MinRed;
		
		private System.Nullable<int> _MinGreen;
		
		private System.Nullable<int> _MinBlue;
		
		private System.Nullable<int> _MaxRed;
		
		private System.Nullable<int> _MaxGreen;
		
		private System.Nullable<int> _MaxBlue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnChartIdChanging(int value);
    partial void OnChartIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnMinRedChanging(System.Nullable<int> value);
    partial void OnMinRedChanged();
    partial void OnMinGreenChanging(System.Nullable<int> value);
    partial void OnMinGreenChanged();
    partial void OnMinBlueChanging(System.Nullable<int> value);
    partial void OnMinBlueChanged();
    partial void OnMaxRedChanging(System.Nullable<int> value);
    partial void OnMaxRedChanged();
    partial void OnMaxGreenChanging(System.Nullable<int> value);
    partial void OnMaxGreenChanged();
    partial void OnMaxBlueChanging(System.Nullable<int> value);
    partial void OnMaxBlueChanged();
    #endregion
		
		public Roadmap_Category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChartId", DbType="Int NOT NULL")]
		public int ChartId
		{
			get
			{
				return this._ChartId;
			}
			set
			{
				if ((this._ChartId != value))
				{
					this.OnChartIdChanging(value);
					this.SendPropertyChanging();
					this._ChartId = value;
					this.SendPropertyChanged("ChartId");
					this.OnChartIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinRed", DbType="Int")]
		public System.Nullable<int> MinRed
		{
			get
			{
				return this._MinRed;
			}
			set
			{
				if ((this._MinRed != value))
				{
					this.OnMinRedChanging(value);
					this.SendPropertyChanging();
					this._MinRed = value;
					this.SendPropertyChanged("MinRed");
					this.OnMinRedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinGreen", DbType="Int")]
		public System.Nullable<int> MinGreen
		{
			get
			{
				return this._MinGreen;
			}
			set
			{
				if ((this._MinGreen != value))
				{
					this.OnMinGreenChanging(value);
					this.SendPropertyChanging();
					this._MinGreen = value;
					this.SendPropertyChanged("MinGreen");
					this.OnMinGreenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinBlue", DbType="Int")]
		public System.Nullable<int> MinBlue
		{
			get
			{
				return this._MinBlue;
			}
			set
			{
				if ((this._MinBlue != value))
				{
					this.OnMinBlueChanging(value);
					this.SendPropertyChanging();
					this._MinBlue = value;
					this.SendPropertyChanged("MinBlue");
					this.OnMinBlueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxRed", DbType="Int")]
		public System.Nullable<int> MaxRed
		{
			get
			{
				return this._MaxRed;
			}
			set
			{
				if ((this._MaxRed != value))
				{
					this.OnMaxRedChanging(value);
					this.SendPropertyChanging();
					this._MaxRed = value;
					this.SendPropertyChanged("MaxRed");
					this.OnMaxRedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxGreen", DbType="Int")]
		public System.Nullable<int> MaxGreen
		{
			get
			{
				return this._MaxGreen;
			}
			set
			{
				if ((this._MaxGreen != value))
				{
					this.OnMaxGreenChanging(value);
					this.SendPropertyChanging();
					this._MaxGreen = value;
					this.SendPropertyChanged("MaxGreen");
					this.OnMaxGreenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxBlue", DbType="Int")]
		public System.Nullable<int> MaxBlue
		{
			get
			{
				return this._MaxBlue;
			}
			set
			{
				if ((this._MaxBlue != value))
				{
					this.OnMaxBlueChanging(value);
					this.SendPropertyChanging();
					this._MaxBlue = value;
					this.SendPropertyChanged("MaxBlue");
					this.OnMaxBlueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roadmap_Charts")]
	public partial class Roadmap_Chart : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Title;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    #endregion
		
		public Roadmap_Chart()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(250)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roadmap_Entries")]
	public partial class Roadmap_Entry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _ChartId;
		
		private int _CategoryId;
		
		private string _Title;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnChartIdChanging(int value);
    partial void OnChartIdChanged();
    partial void OnCategoryIdChanging(int value);
    partial void OnCategoryIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    #endregion
		
		public Roadmap_Entry()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChartId", DbType="Int NOT NULL")]
		public int ChartId
		{
			get
			{
				return this._ChartId;
			}
			set
			{
				if ((this._ChartId != value))
				{
					this.OnChartIdChanging(value);
					this.SendPropertyChanging();
					this._ChartId = value;
					this.SendPropertyChanged("ChartId");
					this.OnChartIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="Int NOT NULL")]
		public int CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this.OnCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._CategoryId = value;
					this.SendPropertyChanged("CategoryId");
					this.OnCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roadmap_Timeframes")]
	public partial class Roadmap_Timeframe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _ChartId;
		
		private string _Title;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnChartIdChanging(int value);
    partial void OnChartIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    #endregion
		
		public Roadmap_Timeframe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChartId", DbType="Int NOT NULL")]
		public int ChartId
		{
			get
			{
				return this._ChartId;
			}
			set
			{
				if ((this._ChartId != value))
				{
					this.OnChartIdChanging(value);
					this.SendPropertyChanging();
					this._ChartId = value;
					this.SendPropertyChanged("ChartId");
					this.OnChartIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roadmap_Values")]
	public partial class Roadmap_Value : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _ChartId;
		
		private int _EntryId;
		
		private int _TimeframeId;
		
		private decimal _Value;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnChartIdChanging(int value);
    partial void OnChartIdChanged();
    partial void OnEntryIdChanging(int value);
    partial void OnEntryIdChanged();
    partial void OnTimeframeIdChanging(int value);
    partial void OnTimeframeIdChanged();
    partial void OnValueChanging(decimal value);
    partial void OnValueChanged();
    #endregion
		
		public Roadmap_Value()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChartId", DbType="Int NOT NULL")]
		public int ChartId
		{
			get
			{
				return this._ChartId;
			}
			set
			{
				if ((this._ChartId != value))
				{
					this.OnChartIdChanging(value);
					this.SendPropertyChanging();
					this._ChartId = value;
					this.SendPropertyChanged("ChartId");
					this.OnChartIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryId", DbType="Int NOT NULL")]
		public int EntryId
		{
			get
			{
				return this._EntryId;
			}
			set
			{
				if ((this._EntryId != value))
				{
					this.OnEntryIdChanging(value);
					this.SendPropertyChanging();
					this._EntryId = value;
					this.SendPropertyChanged("EntryId");
					this.OnEntryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeframeId", DbType="Int NOT NULL")]
		public int TimeframeId
		{
			get
			{
				return this._TimeframeId;
			}
			set
			{
				if ((this._TimeframeId != value))
				{
					this.OnTimeframeIdChanging(value);
					this.SendPropertyChanging();
					this._TimeframeId = value;
					this.SendPropertyChanged("TimeframeId");
					this.OnTimeframeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="Decimal(18,4) NOT NULL")]
		public decimal Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IpmSuggestion")]
	public partial class IpmSuggestion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _SubQuestionId;
		
		private string _Suggestion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSubQuestionIdChanging(int value);
    partial void OnSubQuestionIdChanged();
    partial void OnSuggestionChanging(string value);
    partial void OnSuggestionChanged();
    #endregion
		
		public IpmSuggestion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubQuestionId", DbType="Int NOT NULL")]
		public int SubQuestionId
		{
			get
			{
				return this._SubQuestionId;
			}
			set
			{
				if ((this._SubQuestionId != value))
				{
					this.OnSubQuestionIdChanging(value);
					this.SendPropertyChanging();
					this._SubQuestionId = value;
					this.SendPropertyChanged("SubQuestionId");
					this.OnSubQuestionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suggestion", DbType="NVarChar(MAX)")]
		public string Suggestion
		{
			get
			{
				return this._Suggestion;
			}
			set
			{
				if ((this._Suggestion != value))
				{
					this.OnSuggestionChanging(value);
					this.SendPropertyChanging();
					this._Suggestion = value;
					this.SendPropertyChanged("Suggestion");
					this.OnSuggestionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SelectFromIpmOptionResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _SurveyId;
		
		private System.Nullable<int> _QuestionId;
		
		private System.Nullable<int> _SubQuestionId;
		
		private string _OptionType;
		
		private string _OptionText;
		
		private string _Weighting;
		
		public SelectFromIpmOptionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyId", DbType="Int")]
		public System.Nullable<int> SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					this._SurveyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", DbType="Int")]
		public System.Nullable<int> QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					this._QuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubQuestionId", DbType="Int")]
		public System.Nullable<int> SubQuestionId
		{
			get
			{
				return this._SubQuestionId;
			}
			set
			{
				if ((this._SubQuestionId != value))
				{
					this._SubQuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionType", DbType="NVarChar(50)")]
		public string OptionType
		{
			get
			{
				return this._OptionType;
			}
			set
			{
				if ((this._OptionType != value))
				{
					this._OptionType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionText", DbType="NVarChar(200)")]
		public string OptionText
		{
			get
			{
				return this._OptionText;
			}
			set
			{
				if ((this._OptionText != value))
				{
					this._OptionText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weighting", DbType="NVarChar(10)")]
		public string Weighting
		{
			get
			{
				return this._Weighting;
			}
			set
			{
				if ((this._Weighting != value))
				{
					this._Weighting = value;
				}
			}
		}
	}
	
	public partial class SelectFromIpmOptionBySubQuestionIdResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _SurveyId;
		
		private System.Nullable<int> _QuestionId;
		
		private System.Nullable<int> _SubQuestionId;
		
		private string _OptionType;
		
		private string _OptionText;
		
		private string _Weighting;
		
		public SelectFromIpmOptionBySubQuestionIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyId", DbType="Int")]
		public System.Nullable<int> SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					this._SurveyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", DbType="Int")]
		public System.Nullable<int> QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					this._QuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubQuestionId", DbType="Int")]
		public System.Nullable<int> SubQuestionId
		{
			get
			{
				return this._SubQuestionId;
			}
			set
			{
				if ((this._SubQuestionId != value))
				{
					this._SubQuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionType", DbType="NVarChar(50)")]
		public string OptionType
		{
			get
			{
				return this._OptionType;
			}
			set
			{
				if ((this._OptionType != value))
				{
					this._OptionType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionText", DbType="NVarChar(200)")]
		public string OptionText
		{
			get
			{
				return this._OptionText;
			}
			set
			{
				if ((this._OptionText != value))
				{
					this._OptionText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weighting", DbType="NVarChar(10)")]
		public string Weighting
		{
			get
			{
				return this._Weighting;
			}
			set
			{
				if ((this._Weighting != value))
				{
					this._Weighting = value;
				}
			}
		}
	}
	
	public partial class SelectFromIpmQuestionResult
	{
		
		private int _Id;
		
		private int _SurveyId;
		
		private int _QuestionNumber;
		
		private string _QuestionText;
		
		private bool _IsWeighted;
		
		private bool _HasSubQuestions;
		
		private string _BeforeText;
		
		private string _AfterText;
		
		public SelectFromIpmQuestionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyId", DbType="Int NOT NULL")]
		public int SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					this._SurveyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionNumber", DbType="Int NOT NULL")]
		public int QuestionNumber
		{
			get
			{
				return this._QuestionNumber;
			}
			set
			{
				if ((this._QuestionNumber != value))
				{
					this._QuestionNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionText", DbType="NVarChar(500)")]
		public string QuestionText
		{
			get
			{
				return this._QuestionText;
			}
			set
			{
				if ((this._QuestionText != value))
				{
					this._QuestionText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsWeighted", DbType="Bit NOT NULL")]
		public bool IsWeighted
		{
			get
			{
				return this._IsWeighted;
			}
			set
			{
				if ((this._IsWeighted != value))
				{
					this._IsWeighted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasSubQuestions", DbType="Bit NOT NULL")]
		public bool HasSubQuestions
		{
			get
			{
				return this._HasSubQuestions;
			}
			set
			{
				if ((this._HasSubQuestions != value))
				{
					this._HasSubQuestions = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeforeText", DbType="NVarChar(500)")]
		public string BeforeText
		{
			get
			{
				return this._BeforeText;
			}
			set
			{
				if ((this._BeforeText != value))
				{
					this._BeforeText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AfterText", DbType="NVarChar(500)")]
		public string AfterText
		{
			get
			{
				return this._AfterText;
			}
			set
			{
				if ((this._AfterText != value))
				{
					this._AfterText = value;
				}
			}
		}
	}
	
	public partial class SelectFromIpmQuestionByQuestionIdResult
	{
		
		private int _Id;
		
		private int _SurveyId;
		
		private int _QuestionNumber;
		
		private string _QuestionText;
		
		private bool _IsWeighted;
		
		private bool _HasSubQuestions;
		
		private string _BeforeText;
		
		private string _AfterText;
		
		public SelectFromIpmQuestionByQuestionIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyId", DbType="Int NOT NULL")]
		public int SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					this._SurveyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionNumber", DbType="Int NOT NULL")]
		public int QuestionNumber
		{
			get
			{
				return this._QuestionNumber;
			}
			set
			{
				if ((this._QuestionNumber != value))
				{
					this._QuestionNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionText", DbType="NVarChar(500)")]
		public string QuestionText
		{
			get
			{
				return this._QuestionText;
			}
			set
			{
				if ((this._QuestionText != value))
				{
					this._QuestionText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsWeighted", DbType="Bit NOT NULL")]
		public bool IsWeighted
		{
			get
			{
				return this._IsWeighted;
			}
			set
			{
				if ((this._IsWeighted != value))
				{
					this._IsWeighted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasSubQuestions", DbType="Bit NOT NULL")]
		public bool HasSubQuestions
		{
			get
			{
				return this._HasSubQuestions;
			}
			set
			{
				if ((this._HasSubQuestions != value))
				{
					this._HasSubQuestions = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeforeText", DbType="NVarChar(500)")]
		public string BeforeText
		{
			get
			{
				return this._BeforeText;
			}
			set
			{
				if ((this._BeforeText != value))
				{
					this._BeforeText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AfterText", DbType="NVarChar(500)")]
		public string AfterText
		{
			get
			{
				return this._AfterText;
			}
			set
			{
				if ((this._AfterText != value))
				{
					this._AfterText = value;
				}
			}
		}
	}
	
	public partial class SelectFromIpmResultResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _UserId;
		
		private System.Nullable<int> _SurveyId;
		
		private System.Nullable<int> _SubmissionId;
		
		private string _OptionText;
		
		private System.Nullable<int> _OptionId;
		
		private System.Nullable<int> _SubQuestionId;
		
		private System.Nullable<int> _QuestionId;
		
		private string _Weighting;
		
		public SelectFromIpmResultResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyId", DbType="Int")]
		public System.Nullable<int> SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					this._SurveyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionId", DbType="Int")]
		public System.Nullable<int> SubmissionId
		{
			get
			{
				return this._SubmissionId;
			}
			set
			{
				if ((this._SubmissionId != value))
				{
					this._SubmissionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionText", DbType="NVarChar(200)")]
		public string OptionText
		{
			get
			{
				return this._OptionText;
			}
			set
			{
				if ((this._OptionText != value))
				{
					this._OptionText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionId", DbType="Int")]
		public System.Nullable<int> OptionId
		{
			get
			{
				return this._OptionId;
			}
			set
			{
				if ((this._OptionId != value))
				{
					this._OptionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubQuestionId", DbType="Int")]
		public System.Nullable<int> SubQuestionId
		{
			get
			{
				return this._SubQuestionId;
			}
			set
			{
				if ((this._SubQuestionId != value))
				{
					this._SubQuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", DbType="Int")]
		public System.Nullable<int> QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					this._QuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weighting", DbType="NVarChar(10)")]
		public string Weighting
		{
			get
			{
				return this._Weighting;
			}
			set
			{
				if ((this._Weighting != value))
				{
					this._Weighting = value;
				}
			}
		}
	}
	
	public partial class SelectFromIpmResultBySubmissionIdResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _UserId;
		
		private System.Nullable<int> _SurveyId;
		
		private System.Nullable<int> _SubmissionId;
		
		private string _OptionText;
		
		private System.Nullable<int> _OptionId;
		
		private System.Nullable<int> _SubQuestionId;
		
		private System.Nullable<int> _QuestionId;
		
		private string _Weighting;
		
		public SelectFromIpmResultBySubmissionIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyId", DbType="Int")]
		public System.Nullable<int> SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					this._SurveyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionId", DbType="Int")]
		public System.Nullable<int> SubmissionId
		{
			get
			{
				return this._SubmissionId;
			}
			set
			{
				if ((this._SubmissionId != value))
				{
					this._SubmissionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionText", DbType="NVarChar(200)")]
		public string OptionText
		{
			get
			{
				return this._OptionText;
			}
			set
			{
				if ((this._OptionText != value))
				{
					this._OptionText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionId", DbType="Int")]
		public System.Nullable<int> OptionId
		{
			get
			{
				return this._OptionId;
			}
			set
			{
				if ((this._OptionId != value))
				{
					this._OptionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubQuestionId", DbType="Int")]
		public System.Nullable<int> SubQuestionId
		{
			get
			{
				return this._SubQuestionId;
			}
			set
			{
				if ((this._SubQuestionId != value))
				{
					this._SubQuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", DbType="Int")]
		public System.Nullable<int> QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					this._QuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weighting", DbType="NVarChar(10)")]
		public string Weighting
		{
			get
			{
				return this._Weighting;
			}
			set
			{
				if ((this._Weighting != value))
				{
					this._Weighting = value;
				}
			}
		}
	}
	
	public partial class SelectFromIpmResultByUserIdResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _UserId;
		
		private System.Nullable<int> _SurveyId;
		
		private System.Nullable<int> _SubmissionId;
		
		private string _OptionText;
		
		private System.Nullable<int> _OptionId;
		
		private System.Nullable<int> _SubQuestionId;
		
		private System.Nullable<int> _QuestionId;
		
		private string _Weighting;
		
		public SelectFromIpmResultByUserIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyId", DbType="Int")]
		public System.Nullable<int> SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					this._SurveyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionId", DbType="Int")]
		public System.Nullable<int> SubmissionId
		{
			get
			{
				return this._SubmissionId;
			}
			set
			{
				if ((this._SubmissionId != value))
				{
					this._SubmissionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionText", DbType="NVarChar(200)")]
		public string OptionText
		{
			get
			{
				return this._OptionText;
			}
			set
			{
				if ((this._OptionText != value))
				{
					this._OptionText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionId", DbType="Int")]
		public System.Nullable<int> OptionId
		{
			get
			{
				return this._OptionId;
			}
			set
			{
				if ((this._OptionId != value))
				{
					this._OptionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubQuestionId", DbType="Int")]
		public System.Nullable<int> SubQuestionId
		{
			get
			{
				return this._SubQuestionId;
			}
			set
			{
				if ((this._SubQuestionId != value))
				{
					this._SubQuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", DbType="Int")]
		public System.Nullable<int> QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					this._QuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weighting", DbType="NVarChar(10)")]
		public string Weighting
		{
			get
			{
				return this._Weighting;
			}
			set
			{
				if ((this._Weighting != value))
				{
					this._Weighting = value;
				}
			}
		}
	}
	
	public partial class SelectFromIpmSubquestionResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _SurveyId;
		
		private System.Nullable<int> _QuestionId;
		
		private System.Nullable<int> _SubQuestionNumber;
		
		private string _SubQuestionText;
		
		private string _SubQuestionType;
		
		private string _BeforeText;
		
		private string _AfterText;
		
		public SelectFromIpmSubquestionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyId", DbType="Int")]
		public System.Nullable<int> SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					this._SurveyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", DbType="Int")]
		public System.Nullable<int> QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					this._QuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubQuestionNumber", DbType="Int")]
		public System.Nullable<int> SubQuestionNumber
		{
			get
			{
				return this._SubQuestionNumber;
			}
			set
			{
				if ((this._SubQuestionNumber != value))
				{
					this._SubQuestionNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubQuestionText", DbType="NVarChar(500)")]
		public string SubQuestionText
		{
			get
			{
				return this._SubQuestionText;
			}
			set
			{
				if ((this._SubQuestionText != value))
				{
					this._SubQuestionText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubQuestionType", DbType="NVarChar(50)")]
		public string SubQuestionType
		{
			get
			{
				return this._SubQuestionType;
			}
			set
			{
				if ((this._SubQuestionType != value))
				{
					this._SubQuestionType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeforeText", DbType="NVarChar(500)")]
		public string BeforeText
		{
			get
			{
				return this._BeforeText;
			}
			set
			{
				if ((this._BeforeText != value))
				{
					this._BeforeText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AfterText", DbType="NVarChar(500)")]
		public string AfterText
		{
			get
			{
				return this._AfterText;
			}
			set
			{
				if ((this._AfterText != value))
				{
					this._AfterText = value;
				}
			}
		}
	}
	
	public partial class SelectFromIpmSubquestionByQuestionIdResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _SurveyId;
		
		private System.Nullable<int> _QuestionId;
		
		private System.Nullable<int> _SubQuestionNumber;
		
		private string _SubQuestionText;
		
		private string _SubQuestionType;
		
		private string _BeforeText;
		
		private string _AfterText;
		
		public SelectFromIpmSubquestionByQuestionIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyId", DbType="Int")]
		public System.Nullable<int> SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					this._SurveyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", DbType="Int")]
		public System.Nullable<int> QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					this._QuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubQuestionNumber", DbType="Int")]
		public System.Nullable<int> SubQuestionNumber
		{
			get
			{
				return this._SubQuestionNumber;
			}
			set
			{
				if ((this._SubQuestionNumber != value))
				{
					this._SubQuestionNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubQuestionText", DbType="NVarChar(500)")]
		public string SubQuestionText
		{
			get
			{
				return this._SubQuestionText;
			}
			set
			{
				if ((this._SubQuestionText != value))
				{
					this._SubQuestionText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubQuestionType", DbType="NVarChar(50)")]
		public string SubQuestionType
		{
			get
			{
				return this._SubQuestionType;
			}
			set
			{
				if ((this._SubQuestionType != value))
				{
					this._SubQuestionType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeforeText", DbType="NVarChar(500)")]
		public string BeforeText
		{
			get
			{
				return this._BeforeText;
			}
			set
			{
				if ((this._BeforeText != value))
				{
					this._BeforeText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AfterText", DbType="NVarChar(500)")]
		public string AfterText
		{
			get
			{
				return this._AfterText;
			}
			set
			{
				if ((this._AfterText != value))
				{
					this._AfterText = value;
				}
			}
		}
	}
	
	public partial class SelectFromIpmSurveyByIdResult
	{
		
		private int _Id;
		
		private string _Description;
		
		public SelectFromIpmSurveyByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(200)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	public partial class SelectFromIpmUserResult
	{
		
		private int _Id;
		
		private string _FirstName;
		
		private string _Surname;
		
		private string _EmailAddress;
		
		private string _Company;
		
		private string _AddressLineOne;
		
		private string _AddressLineTwo;
		
		private string _AddressLineThree;
		
		private string _Town;
		
		private string _County;
		
		private string _PostCode;
		
		private System.Nullable<bool> _IsMember;
		
		private string _MembershipNumber;
		
		private System.Nullable<System.DateTime> _DateAdded;
		
		public SelectFromIpmUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(50)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(100)")]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(255)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this._Company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLineOne", DbType="NVarChar(255)")]
		public string AddressLineOne
		{
			get
			{
				return this._AddressLineOne;
			}
			set
			{
				if ((this._AddressLineOne != value))
				{
					this._AddressLineOne = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLineTwo", DbType="NVarChar(255)")]
		public string AddressLineTwo
		{
			get
			{
				return this._AddressLineTwo;
			}
			set
			{
				if ((this._AddressLineTwo != value))
				{
					this._AddressLineTwo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLineThree", DbType="NVarChar(255)")]
		public string AddressLineThree
		{
			get
			{
				return this._AddressLineThree;
			}
			set
			{
				if ((this._AddressLineThree != value))
				{
					this._AddressLineThree = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Town", DbType="NVarChar(50)")]
		public string Town
		{
			get
			{
				return this._Town;
			}
			set
			{
				if ((this._Town != value))
				{
					this._Town = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="NVarChar(50)")]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this._County = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostCode", DbType="NVarChar(15)")]
		public string PostCode
		{
			get
			{
				return this._PostCode;
			}
			set
			{
				if ((this._PostCode != value))
				{
					this._PostCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMember", DbType="Bit")]
		public System.Nullable<bool> IsMember
		{
			get
			{
				return this._IsMember;
			}
			set
			{
				if ((this._IsMember != value))
				{
					this._IsMember = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MembershipNumber", DbType="NVarChar(10)")]
		public string MembershipNumber
		{
			get
			{
				return this._MembershipNumber;
			}
			set
			{
				if ((this._MembershipNumber != value))
				{
					this._MembershipNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdded", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateAdded
		{
			get
			{
				return this._DateAdded;
			}
			set
			{
				if ((this._DateAdded != value))
				{
					this._DateAdded = value;
				}
			}
		}
	}
	
	public partial class SelectFromIpmUserByIdResult
	{
		
		private int _Id;
		
		private string _FirstName;
		
		private string _Surname;
		
		private string _EmailAddress;
		
		private string _Company;
		
		private string _AddressLineOne;
		
		private string _AddressLineTwo;
		
		private string _AddressLineThree;
		
		private string _Town;
		
		private string _County;
		
		private string _PostCode;
		
		private System.Nullable<bool> _IsMember;
		
		private string _MembershipNumber;
		
		private System.Nullable<System.DateTime> _DateAdded;
		
		public SelectFromIpmUserByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(50)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(100)")]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(255)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this._Company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLineOne", DbType="NVarChar(255)")]
		public string AddressLineOne
		{
			get
			{
				return this._AddressLineOne;
			}
			set
			{
				if ((this._AddressLineOne != value))
				{
					this._AddressLineOne = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLineTwo", DbType="NVarChar(255)")]
		public string AddressLineTwo
		{
			get
			{
				return this._AddressLineTwo;
			}
			set
			{
				if ((this._AddressLineTwo != value))
				{
					this._AddressLineTwo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLineThree", DbType="NVarChar(255)")]
		public string AddressLineThree
		{
			get
			{
				return this._AddressLineThree;
			}
			set
			{
				if ((this._AddressLineThree != value))
				{
					this._AddressLineThree = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Town", DbType="NVarChar(50)")]
		public string Town
		{
			get
			{
				return this._Town;
			}
			set
			{
				if ((this._Town != value))
				{
					this._Town = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="NVarChar(50)")]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this._County = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostCode", DbType="NVarChar(15)")]
		public string PostCode
		{
			get
			{
				return this._PostCode;
			}
			set
			{
				if ((this._PostCode != value))
				{
					this._PostCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMember", DbType="Bit")]
		public System.Nullable<bool> IsMember
		{
			get
			{
				return this._IsMember;
			}
			set
			{
				if ((this._IsMember != value))
				{
					this._IsMember = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MembershipNumber", DbType="NVarChar(10)")]
		public string MembershipNumber
		{
			get
			{
				return this._MembershipNumber;
			}
			set
			{
				if ((this._MembershipNumber != value))
				{
					this._MembershipNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdded", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateAdded
		{
			get
			{
				return this._DateAdded;
			}
			set
			{
				if ((this._DateAdded != value))
				{
					this._DateAdded = value;
				}
			}
		}
	}
	
	public partial class InsertToIpmUserResult
	{
		
		private int _Id;
		
		public InsertToIpmUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	
	public partial class PostcodeAnyWhereData_CheckForPostcodeResult
	{
		
		private string _Postcode;
		
		private System.Nullable<double> _Latitude;
		
		private System.Nullable<double> _longitude;
		
		private int _Id;
		
		public PostcodeAnyWhereData_CheckForPostcodeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="NVarChar(50)")]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this._Postcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Float")]
		public System.Nullable<double> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this._Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="Float")]
		public System.Nullable<double> longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this._longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	
	public partial class InsertToIpmSubmissionResult
	{
		
		private int _Id;
		
		public InsertToIpmSubmissionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	
	public partial class SelectFromIpmSubmissionResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _SurveyId;
		
		private System.Nullable<int> _UserId;
		
		private System.Nullable<bool> _IsComplete;
		
		private System.Nullable<System.DateTime> _SubmissionDate;
		
		private System.Nullable<System.Guid> _UserGuid;
		
		public SelectFromIpmSubmissionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyId", DbType="Int")]
		public System.Nullable<int> SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					this._SurveyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsComplete", DbType="Bit")]
		public System.Nullable<bool> IsComplete
		{
			get
			{
				return this._IsComplete;
			}
			set
			{
				if ((this._IsComplete != value))
				{
					this._IsComplete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SubmissionDate
		{
			get
			{
				return this._SubmissionDate;
			}
			set
			{
				if ((this._SubmissionDate != value))
				{
					this._SubmissionDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserGuid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserGuid
		{
			get
			{
				return this._UserGuid;
			}
			set
			{
				if ((this._UserGuid != value))
				{
					this._UserGuid = value;
				}
			}
		}
	}
	
	public partial class SelectFromIpmSubmissionByUserIdResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _SurveyId;
		
		private System.Nullable<int> _UserId;
		
		private System.Nullable<bool> _IsComplete;
		
		private System.Nullable<System.DateTime> _SubmissionDate;
		
		private System.Nullable<System.Guid> _UserGuid;
		
		public SelectFromIpmSubmissionByUserIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyId", DbType="Int")]
		public System.Nullable<int> SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					this._SurveyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsComplete", DbType="Bit")]
		public System.Nullable<bool> IsComplete
		{
			get
			{
				return this._IsComplete;
			}
			set
			{
				if ((this._IsComplete != value))
				{
					this._IsComplete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SubmissionDate
		{
			get
			{
				return this._SubmissionDate;
			}
			set
			{
				if ((this._SubmissionDate != value))
				{
					this._SubmissionDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserGuid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserGuid
		{
			get
			{
				return this._UserGuid;
			}
			set
			{
				if ((this._UserGuid != value))
				{
					this._UserGuid = value;
				}
			}
		}
	}
	
	public partial class SelectFromIpmSubmissionByIdResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _SurveyId;
		
		private System.Nullable<int> _UserId;
		
		private System.Nullable<bool> _IsComplete;
		
		private System.Nullable<System.DateTime> _SubmissionDate;
		
		private System.Nullable<System.Guid> _UserGuid;
		
		public SelectFromIpmSubmissionByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyId", DbType="Int")]
		public System.Nullable<int> SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					this._SurveyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsComplete", DbType="Bit")]
		public System.Nullable<bool> IsComplete
		{
			get
			{
				return this._IsComplete;
			}
			set
			{
				if ((this._IsComplete != value))
				{
					this._IsComplete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SubmissionDate
		{
			get
			{
				return this._SubmissionDate;
			}
			set
			{
				if ((this._SubmissionDate != value))
				{
					this._SubmissionDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserGuid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserGuid
		{
			get
			{
				return this._UserGuid;
			}
			set
			{
				if ((this._UserGuid != value))
				{
					this._UserGuid = value;
				}
			}
		}
	}
	
	public partial class SelectFromIpmSubmissionByStatusResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _SurveyId;
		
		private System.Nullable<int> _UserId;
		
		private System.Nullable<bool> _IsComplete;
		
		private System.Nullable<System.DateTime> _SubmissionDate;
		
		public SelectFromIpmSubmissionByStatusResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyId", DbType="Int")]
		public System.Nullable<int> SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					this._SurveyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsComplete", DbType="Bit")]
		public System.Nullable<bool> IsComplete
		{
			get
			{
				return this._IsComplete;
			}
			set
			{
				if ((this._IsComplete != value))
				{
					this._IsComplete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SubmissionDate
		{
			get
			{
				return this._SubmissionDate;
			}
			set
			{
				if ((this._SubmissionDate != value))
				{
					this._SubmissionDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
