#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoWebsites.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NFU_Media_Centre")]
	public partial class MediaLibraryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MediaLibraryDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NFU_Media_CentreConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MediaLibraryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MediaLibraryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MediaLibraryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MediaLibraryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Assets_SelectByFilename")]
		public ISingleResult<Assets_SelectByFilenameResult> Assets_SelectByFilename([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileName", DbType="NVarChar(50)")] string fileName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fileName);
			return ((ISingleResult<Assets_SelectByFilenameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Assets_KeywordsString")]
		public ISingleResult<Assets_KeywordsStringResult> Assets_KeywordsString([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> assetId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), assetId);
			return ((ISingleResult<Assets_KeywordsStringResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AssetToCategories_ByAssetId")]
		public ISingleResult<AssetToCategories_ByAssetIdResult> AssetToCategories_ByAssetId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AssetId", DbType="BigInt")] System.Nullable<long> assetId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryId", DbType="BigInt")] System.Nullable<long> categoryId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), assetId, categoryId);
			return ((ISingleResult<AssetToCategories_ByAssetIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Categories_SelectById")]
		public ISingleResult<Categories_SelectByIdResult> Categories_SelectById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<Categories_SelectByIdResult>)(result.ReturnValue));
		}
	}
	
	public partial class Assets_SelectByFilenameResult
	{
		
		private long _Id;
		
		private string _Description;
		
		private string _Title;
		
		private string _FileLocation;
		
		private string _FileName;
		
		private string _FileExt;
		
		private string _OrgFileName;
		
		private long _AssetTypeId;
		
		private string _UserId;
		
		private string _Source;
		
		private bool _IsActive;
		
		private bool _IsStaffOnly;
		
		private bool _IsWeb;
		
		private bool _IsPrint;
		
		private string _CopyrightName;
		
		private bool _IsCopyright;
		
		private System.DateTime _DateCreated;
		
		private System.Nullable<System.DateTime> _DateTaken;
		
		private string _UploadStatus;
		
		private System.Nullable<int> _Impressions;
		
		private System.Nullable<System.Guid> _OldEktronId;
		
		private string _UsageNotes;
		
		private System.Nullable<System.DateTime> _ExpiryDate;
		
		private System.Nullable<System.DateTime> _LastChanged;
		
		public Assets_SelectByFilenameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(2048)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileLocation", DbType="NVarChar(1024)")]
		public string FileLocation
		{
			get
			{
				return this._FileLocation;
			}
			set
			{
				if ((this._FileLocation != value))
				{
					this._FileLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(50)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileExt", DbType="NVarChar(10)")]
		public string FileExt
		{
			get
			{
				return this._FileExt;
			}
			set
			{
				if ((this._FileExt != value))
				{
					this._FileExt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgFileName", DbType="NVarChar(2048)")]
		public string OrgFileName
		{
			get
			{
				return this._OrgFileName;
			}
			set
			{
				if ((this._OrgFileName != value))
				{
					this._OrgFileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssetTypeId", DbType="BigInt NOT NULL")]
		public long AssetTypeId
		{
			get
			{
				return this._AssetTypeId;
			}
			set
			{
				if ((this._AssetTypeId != value))
				{
					this._AssetTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(50)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this._Source = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsStaffOnly", DbType="Bit NOT NULL")]
		public bool IsStaffOnly
		{
			get
			{
				return this._IsStaffOnly;
			}
			set
			{
				if ((this._IsStaffOnly != value))
				{
					this._IsStaffOnly = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsWeb", DbType="Bit NOT NULL")]
		public bool IsWeb
		{
			get
			{
				return this._IsWeb;
			}
			set
			{
				if ((this._IsWeb != value))
				{
					this._IsWeb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrint", DbType="Bit NOT NULL")]
		public bool IsPrint
		{
			get
			{
				return this._IsPrint;
			}
			set
			{
				if ((this._IsPrint != value))
				{
					this._IsPrint = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CopyrightName", DbType="NVarChar(50)")]
		public string CopyrightName
		{
			get
			{
				return this._CopyrightName;
			}
			set
			{
				if ((this._CopyrightName != value))
				{
					this._CopyrightName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCopyright", DbType="Bit NOT NULL")]
		public bool IsCopyright
		{
			get
			{
				return this._IsCopyright;
			}
			set
			{
				if ((this._IsCopyright != value))
				{
					this._IsCopyright = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTaken", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTaken
		{
			get
			{
				return this._DateTaken;
			}
			set
			{
				if ((this._DateTaken != value))
				{
					this._DateTaken = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadStatus", DbType="NVarChar(50)")]
		public string UploadStatus
		{
			get
			{
				return this._UploadStatus;
			}
			set
			{
				if ((this._UploadStatus != value))
				{
					this._UploadStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impressions", DbType="Int")]
		public System.Nullable<int> Impressions
		{
			get
			{
				return this._Impressions;
			}
			set
			{
				if ((this._Impressions != value))
				{
					this._Impressions = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OldEktronId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> OldEktronId
		{
			get
			{
				return this._OldEktronId;
			}
			set
			{
				if ((this._OldEktronId != value))
				{
					this._OldEktronId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsageNotes", DbType="NVarChar(MAX)")]
		public string UsageNotes
		{
			get
			{
				return this._UsageNotes;
			}
			set
			{
				if ((this._UsageNotes != value))
				{
					this._UsageNotes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryDate", DbType="Date")]
		public System.Nullable<System.DateTime> ExpiryDate
		{
			get
			{
				return this._ExpiryDate;
			}
			set
			{
				if ((this._ExpiryDate != value))
				{
					this._ExpiryDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastChanged", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastChanged
		{
			get
			{
				return this._LastChanged;
			}
			set
			{
				if ((this._LastChanged != value))
				{
					this._LastChanged = value;
				}
			}
		}
	}
	
	public partial class Assets_KeywordsStringResult
	{
		
		private string _Keywords;
		
		private string _KeywordsText;
		
		public Assets_KeywordsStringResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keywords", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Keywords
		{
			get
			{
				return this._Keywords;
			}
			set
			{
				if ((this._Keywords != value))
				{
					this._Keywords = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordsText", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string KeywordsText
		{
			get
			{
				return this._KeywordsText;
			}
			set
			{
				if ((this._KeywordsText != value))
				{
					this._KeywordsText = value;
				}
			}
		}
	}
	
	public partial class AssetToCategories_ByAssetIdResult
	{
		
		private long _Id;
		
		private long _CategoryId;
		
		private long _AssetId;
		
		public AssetToCategories_ByAssetIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="BigInt NOT NULL")]
		public long CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this._CategoryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssetId", DbType="BigInt NOT NULL")]
		public long AssetId
		{
			get
			{
				return this._AssetId;
			}
			set
			{
				if ((this._AssetId != value))
				{
					this._AssetId = value;
				}
			}
		}
	}
	
	public partial class Categories_SelectByIdResult
	{
		
		private long _Id;
		
		private string _Name;
		
		private long _Parent;
		
		private bool _IsActive;
		
		private bool _IsWeb;
		
		private System.Nullable<bool> _IsPrint;
		
		public Categories_SelectByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent", DbType="BigInt NOT NULL")]
		public long Parent
		{
			get
			{
				return this._Parent;
			}
			set
			{
				if ((this._Parent != value))
				{
					this._Parent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsWeb", DbType="Bit NOT NULL")]
		public bool IsWeb
		{
			get
			{
				return this._IsWeb;
			}
			set
			{
				if ((this._IsWeb != value))
				{
					this._IsWeb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrint", DbType="Bit")]
		public System.Nullable<bool> IsPrint
		{
			get
			{
				return this._IsPrint;
			}
			set
			{
				if ((this._IsPrint != value))
				{
					this._IsPrint = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
