#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoWebsites.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NFUWebMisc")]
	public partial class NfuWebMiscDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
        public NfuWebMiscDataContext() :
                base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NFUWebMiscConnectionString"].ConnectionString, mappingSource)
        {
            OnCreated();
        }

		public NfuWebMiscDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NfuWebMiscDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NfuWebMiscDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NfuWebMiscDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_Add")]
		public ISingleResult<Competitions_AddResult> Competitions_Add(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Audience", DbType="NVarChar(MAX)")] string audience, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsAnOffer", DbType="Bit")] System.Nullable<bool> isAnOffer, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsMembersOnly", DbType="Bit")] System.Nullable<bool> isMembersOnly, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostalAddress", DbType="Bit")] System.Nullable<bool> postalAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Postcode", DbType="Bit")] System.Nullable<bool> postcode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneNumber", DbType="Bit")] System.Nullable<bool> phoneNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailAddress", DbType="Bit")] System.Nullable<bool> emailAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Newsletter", DbType="Bit")] System.Nullable<bool> newsletter, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DisplayTitle", DbType="NVarChar(MAX)")] string displayTitle, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DisplayCopy", DbType="NVarChar(MAX)")] string displayCopy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TermsAndConditionsURL", DbType="NVarChar(MAX)")] string termsAndConditionsURL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BackgroundURL", DbType="NVarChar(MAX)")] string backgroundURL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeaturedImageURL", DbType="NVarChar(MAX)")] string featuredImageURL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ThanksTitle", DbType="NVarChar(100)")] string thanksTitle, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ThanksMessage", DbType="NVarChar(MAX)")] string thanksMessage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, isActive, audience, isAnOffer, isMembersOnly, startDate, endDate, postalAddress, postcode, phoneNumber, emailAddress, newsletter, displayTitle, displayCopy, termsAndConditionsURL, backgroundURL, featuredImageURL, thanksTitle, thanksMessage);
			return ((ISingleResult<Competitions_AddResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_Answers_Add")]
		public int Competitions_Answers_Add([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryId", DbType="Int")] System.Nullable<int> entryId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuestionId", DbType="Int")] System.Nullable<int> questionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Answer", DbType="NVarChar(MAX)")] string answer)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), entryId, questionId, answer);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_Answers_GetByEntryId")]
		public ISingleResult<Competitions_Answers_GetByEntryIdResult> Competitions_Answers_GetByEntryId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryId", DbType="Int")] System.Nullable<int> entryId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), entryId);
			return ((ISingleResult<Competitions_Answers_GetByEntryIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_Entries_Add")]
		public ISingleResult<Competitions_Entries_AddResult> Competitions_Entries_Add([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompetitionId", DbType="Int")] System.Nullable<int> competitionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="NVarChar(50)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="NVarChar(50)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="NVarChar(MAX)")] string address1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address2", DbType="NVarChar(MAX)")] string address2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address3", DbType="NVarChar(MAX)")] string address3, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TownCity", DbType="NVarChar(50)")] string townCity, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="County", DbType="NVarChar(50)")] string county, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Postcode", DbType="NVarChar(10)")] string postcode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailAddress", DbType="NVarChar(256)")] string emailAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneNumber", DbType="NVarChar(20)")] string phoneNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SignUpToNewsletter", DbType="Bit")] System.Nullable<bool> signUpToNewsletter, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SocialId", DbType="Int")] System.Nullable<int> socialId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedDate", DbType="DateTime")] System.Nullable<System.DateTime> createdDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MembershipNumber", DbType="NVarChar(MAX)")] string membershipNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), competitionId, firstName, lastName, address1, address2, address3, townCity, county, postcode, emailAddress, phoneNumber, signUpToNewsletter, socialId, createdDate, membershipNumber);
			return ((ISingleResult<Competitions_Entries_AddResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_Entries_Delete")]
		public int Competitions_Entries_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryId", DbType="Int")] System.Nullable<int> entryId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), entryId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_Entries_GetByCompetitionId")]
		public ISingleResult<Competitions_Entries_GetByCompetitionIdResult> Competitions_Entries_GetByCompetitionId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompetitionId", DbType="Int")] System.Nullable<int> competitionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), competitionId);
			return ((ISingleResult<Competitions_Entries_GetByCompetitionIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_Entries_GetCountByCompetitionId")]
		public ISingleResult<Competitions_Entries_GetCountByCompetitionIdResult> Competitions_Entries_GetCountByCompetitionId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompetitionId", DbType="Int")] System.Nullable<int> competitionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), competitionId);
			return ((ISingleResult<Competitions_Entries_GetCountByCompetitionIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_Get")]
		public ISingleResult<Competitions_GetResult> Competitions_Get([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GetActiveOnly", DbType="Bit")] System.Nullable<bool> getActiveOnly, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Audience", DbType="NVarChar(50)")] string audience, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GetOffers", DbType="Bit")] System.Nullable<bool> getOffers)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), getActiveOnly, audience, getOffers);
			return ((ISingleResult<Competitions_GetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_GetById")]
		public ISingleResult<Competitions_GetByIdResult> Competitions_GetById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<Competitions_GetByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_GetByName")]
		public ISingleResult<Competitions_GetByNameResult> Competitions_GetByName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(100)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((ISingleResult<Competitions_GetByNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_Questions_Add")]
		public int Competitions_Questions_Add([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompetitionId", DbType="Int")] System.Nullable<int> competitionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Question", DbType="NVarChar(MAX)")] string question, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsBool", DbType="Bit")] System.Nullable<bool> isBool, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Required", DbType="Bit")] System.Nullable<bool> required)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), competitionId, question, isBool, required);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_Questions_Delete")]
		public int Competitions_Questions_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuestionId", DbType="Int")] System.Nullable<int> questionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), questionId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_Questions_GetByCompetitionId")]
		public ISingleResult<Competitions_Questions_GetByCompetitionIdResult> Competitions_Questions_GetByCompetitionId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompetitionId", DbType="Int")] System.Nullable<int> competitionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), competitionId);
			return ((ISingleResult<Competitions_Questions_GetByCompetitionIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_Questions_GetById")]
		public ISingleResult<Competitions_Questions_GetByIdResult> Competitions_Questions_GetById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<Competitions_Questions_GetByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_Questions_Update")]
		public int Competitions_Questions_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuestionId", DbType="Int")] System.Nullable<int> questionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Question", DbType="NVarChar(MAX)")] string question, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsBool", DbType="Bit")] System.Nullable<bool> isBool, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Required", DbType="Bit")] System.Nullable<bool> required)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), questionId, question, isBool, required);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_Update")]
		public ISingleResult<Competitions_UpdateResult> Competitions_Update(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryId", DbType="Int")] System.Nullable<int> entryId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Audience", DbType="NVarChar(MAX)")] string audience, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsAnOffer", DbType="Bit")] System.Nullable<bool> isAnOffer, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsMembersOnly", DbType="Bit")] System.Nullable<bool> isMembersOnly, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostalAddress", DbType="Bit")] System.Nullable<bool> postalAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Postcode", DbType="Bit")] System.Nullable<bool> postcode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneNumber", DbType="Bit")] System.Nullable<bool> phoneNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailAddress", DbType="Bit")] System.Nullable<bool> emailAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Newsletter", DbType="Bit")] System.Nullable<bool> newsletter, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DisplayTitle", DbType="NVarChar(MAX)")] string displayTitle, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DisplayCopy", DbType="NVarChar(MAX)")] string displayCopy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TermsAndConditionsURL", DbType="NVarChar(MAX)")] string termsAndConditionsURL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BackgroundURL", DbType="NVarChar(MAX)")] string backgroundURL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeaturedImageURL", DbType="NVarChar(MAX)")] string featuredImageURL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ThanksTitle", DbType="NVarChar(100)")] string thanksTitle, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ThanksMessage", DbType="NVarChar(MAX)")] string thanksMessage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), entryId, name, isActive, audience, isAnOffer, isMembersOnly, startDate, endDate, postalAddress, postcode, phoneNumber, emailAddress, newsletter, displayTitle, displayCopy, termsAndConditionsURL, backgroundURL, featuredImageURL, thanksTitle, thanksMessage);
			return ((ISingleResult<Competitions_UpdateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_UpdateStatus")]
		public int Competitions_UpdateStatus([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompetitionId", DbType="Int")] System.Nullable<int> competitionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsDeleted", DbType="Bit")] System.Nullable<bool> isDeleted, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), competitionId, isDeleted, isActive);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Competitions_Entries_Add_TMP")]
		public ISingleResult<Competitions_Entries_Add_TMPResult> Competitions_Entries_Add_TMP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompetitionId", DbType="Int")] System.Nullable<int> competitionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="NVarChar(50)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="NVarChar(50)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="NVarChar(MAX)")] string address1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address2", DbType="NVarChar(MAX)")] string address2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address3", DbType="NVarChar(MAX)")] string address3, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TownCity", DbType="NVarChar(50)")] string townCity, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="County", DbType="NVarChar(50)")] string county, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Postcode", DbType="NVarChar(10)")] string postcode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailAddress", DbType="NVarChar(256)")] string emailAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneNumber", DbType="NVarChar(20)")] string phoneNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SignUpToNewsletter", DbType="Bit")] System.Nullable<bool> signUpToNewsletter, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SocialId", DbType="Int")] System.Nullable<int> socialId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedDate", DbType="DateTime")] System.Nullable<System.DateTime> createdDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MembershipNumber", DbType="NVarChar(MAX)")] string membershipNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), competitionId, firstName, lastName, address1, address2, address3, townCity, county, postcode, emailAddress, phoneNumber, signUpToNewsletter, socialId, createdDate, membershipNumber);
			return ((ISingleResult<Competitions_Entries_Add_TMPResult>)(result.ReturnValue));
		}
	}
	
	public partial class Competitions_AddResult
	{
		
		private System.Nullable<decimal> _Column1;
		
		public Competitions_AddResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class Competitions_Answers_GetByEntryIdResult
	{
		
		private int _Id;
		
		private int _EntryId;
		
		private int _QuestionId;
		
		private string _Answer;
		
		public Competitions_Answers_GetByEntryIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryId", DbType="Int NOT NULL")]
		public int EntryId
		{
			get
			{
				return this._EntryId;
			}
			set
			{
				if ((this._EntryId != value))
				{
					this._EntryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", DbType="Int NOT NULL")]
		public int QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					this._QuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this._Answer = value;
				}
			}
		}
	}
	
	public partial class Competitions_Entries_AddResult
	{
		
		private System.Nullable<decimal> _Column1;
		
		public Competitions_Entries_AddResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class Competitions_Entries_GetByCompetitionIdResult
	{
		
		private int _Id;
		
		private int _CompetitionId;
		
		private string _FirstName;
		
		private string _Surname;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _TownCity;
		
		private string _County;
		
		private string _Postcode;
		
		private string _EmailAddress;
		
		private string _PhoneNumber;
		
		private bool _SignUpToNewsletter;
		
		private int _SocialId;
		
		private System.DateTime _CreatedDate;
		
		private string _MembershipNumber;
		
		public Competitions_Entries_GetByCompetitionIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompetitionId", DbType="Int NOT NULL")]
		public int CompetitionId
		{
			get
			{
				return this._CompetitionId;
			}
			set
			{
				if ((this._CompetitionId != value))
				{
					this._CompetitionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(50)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="NVarChar(MAX)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="NVarChar(MAX)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this._Address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="NVarChar(MAX)")]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this._Address3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TownCity", DbType="NVarChar(50)")]
		public string TownCity
		{
			get
			{
				return this._TownCity;
			}
			set
			{
				if ((this._TownCity != value))
				{
					this._TownCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="NVarChar(50)")]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this._County = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="NVarChar(10)")]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this._Postcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(256)")]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(20)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignUpToNewsletter", DbType="Bit NOT NULL")]
		public bool SignUpToNewsletter
		{
			get
			{
				return this._SignUpToNewsletter;
			}
			set
			{
				if ((this._SignUpToNewsletter != value))
				{
					this._SignUpToNewsletter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SocialId", DbType="Int NOT NULL")]
		public int SocialId
		{
			get
			{
				return this._SocialId;
			}
			set
			{
				if ((this._SocialId != value))
				{
					this._SocialId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MembershipNumber", DbType="NVarChar(MAX)")]
		public string MembershipNumber
		{
			get
			{
				return this._MembershipNumber;
			}
			set
			{
				if ((this._MembershipNumber != value))
				{
					this._MembershipNumber = value;
				}
			}
		}
	}
	
	public partial class Competitions_Entries_GetCountByCompetitionIdResult
	{
		
		private System.Nullable<int> _Entries;
		
		public Competitions_Entries_GetCountByCompetitionIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entries", DbType="Int")]
		public System.Nullable<int> Entries
		{
			get
			{
				return this._Entries;
			}
			set
			{
				if ((this._Entries != value))
				{
					this._Entries = value;
				}
			}
		}
	}
	
	public partial class Competitions_GetResult
	{
		
		private int _Id;
		
		private string _Name;
		
		private bool _IsActive;
		
		private bool _IsMembersOnly;
		
		private string _Audience;
		
		private bool _IsAnOffer;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private bool _PostalAddress;
		
		private bool _Postcode;
		
		private bool _PhoneNumber;
		
		private bool _EmailAddress;
		
		private bool _Newsletter;
		
		private string _DisplayTitle;
		
		private string _DisplayCopy;
		
		private string _TermsAndConditionsURL;
		
		private string _BackgroundURL;
		
		private string _FeaturedImageURL;
		
		private string _ThanksTitle;
		
		private string _ThanksMessage;
		
		private bool _IsDeleted;
		
		public Competitions_GetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMembersOnly", DbType="Bit NOT NULL")]
		public bool IsMembersOnly
		{
			get
			{
				return this._IsMembersOnly;
			}
			set
			{
				if ((this._IsMembersOnly != value))
				{
					this._IsMembersOnly = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Audience", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Audience
		{
			get
			{
				return this._Audience;
			}
			set
			{
				if ((this._Audience != value))
				{
					this._Audience = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAnOffer", DbType="Bit NOT NULL")]
		public bool IsAnOffer
		{
			get
			{
				return this._IsAnOffer;
			}
			set
			{
				if ((this._IsAnOffer != value))
				{
					this._IsAnOffer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalAddress", DbType="Bit NOT NULL")]
		public bool PostalAddress
		{
			get
			{
				return this._PostalAddress;
			}
			set
			{
				if ((this._PostalAddress != value))
				{
					this._PostalAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="Bit NOT NULL")]
		public bool Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this._Postcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="Bit NOT NULL")]
		public bool PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="Bit NOT NULL")]
		public bool EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Newsletter", DbType="Bit NOT NULL")]
		public bool Newsletter
		{
			get
			{
				return this._Newsletter;
			}
			set
			{
				if ((this._Newsletter != value))
				{
					this._Newsletter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayTitle", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DisplayTitle
		{
			get
			{
				return this._DisplayTitle;
			}
			set
			{
				if ((this._DisplayTitle != value))
				{
					this._DisplayTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayCopy", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DisplayCopy
		{
			get
			{
				return this._DisplayCopy;
			}
			set
			{
				if ((this._DisplayCopy != value))
				{
					this._DisplayCopy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TermsAndConditionsURL", DbType="NVarChar(MAX)")]
		public string TermsAndConditionsURL
		{
			get
			{
				return this._TermsAndConditionsURL;
			}
			set
			{
				if ((this._TermsAndConditionsURL != value))
				{
					this._TermsAndConditionsURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackgroundURL", DbType="NVarChar(MAX)")]
		public string BackgroundURL
		{
			get
			{
				return this._BackgroundURL;
			}
			set
			{
				if ((this._BackgroundURL != value))
				{
					this._BackgroundURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeaturedImageURL", DbType="NVarChar(MAX)")]
		public string FeaturedImageURL
		{
			get
			{
				return this._FeaturedImageURL;
			}
			set
			{
				if ((this._FeaturedImageURL != value))
				{
					this._FeaturedImageURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanksTitle", DbType="NVarChar(100)")]
		public string ThanksTitle
		{
			get
			{
				return this._ThanksTitle;
			}
			set
			{
				if ((this._ThanksTitle != value))
				{
					this._ThanksTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanksMessage", DbType="NVarChar(MAX)")]
		public string ThanksMessage
		{
			get
			{
				return this._ThanksMessage;
			}
			set
			{
				if ((this._ThanksMessage != value))
				{
					this._ThanksMessage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
	}
	
	public partial class Competitions_GetByIdResult
	{
		
		private int _Id;
		
		private string _Name;
		
		private bool _IsActive;
		
		private bool _IsMembersOnly;
		
		private string _Audience;
		
		private bool _IsAnOffer;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private bool _PostalAddress;
		
		private bool _Postcode;
		
		private bool _PhoneNumber;
		
		private bool _EmailAddress;
		
		private bool _Newsletter;
		
		private string _DisplayTitle;
		
		private string _DisplayCopy;
		
		private string _TermsAndConditionsURL;
		
		private string _BackgroundURL;
		
		private string _FeaturedImageURL;
		
		private string _ThanksTitle;
		
		private string _ThanksMessage;
		
		private bool _IsDeleted;
		
		public Competitions_GetByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMembersOnly", DbType="Bit NOT NULL")]
		public bool IsMembersOnly
		{
			get
			{
				return this._IsMembersOnly;
			}
			set
			{
				if ((this._IsMembersOnly != value))
				{
					this._IsMembersOnly = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Audience", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Audience
		{
			get
			{
				return this._Audience;
			}
			set
			{
				if ((this._Audience != value))
				{
					this._Audience = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAnOffer", DbType="Bit NOT NULL")]
		public bool IsAnOffer
		{
			get
			{
				return this._IsAnOffer;
			}
			set
			{
				if ((this._IsAnOffer != value))
				{
					this._IsAnOffer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalAddress", DbType="Bit NOT NULL")]
		public bool PostalAddress
		{
			get
			{
				return this._PostalAddress;
			}
			set
			{
				if ((this._PostalAddress != value))
				{
					this._PostalAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="Bit NOT NULL")]
		public bool Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this._Postcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="Bit NOT NULL")]
		public bool PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="Bit NOT NULL")]
		public bool EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Newsletter", DbType="Bit NOT NULL")]
		public bool Newsletter
		{
			get
			{
				return this._Newsletter;
			}
			set
			{
				if ((this._Newsletter != value))
				{
					this._Newsletter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayTitle", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DisplayTitle
		{
			get
			{
				return this._DisplayTitle;
			}
			set
			{
				if ((this._DisplayTitle != value))
				{
					this._DisplayTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayCopy", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DisplayCopy
		{
			get
			{
				return this._DisplayCopy;
			}
			set
			{
				if ((this._DisplayCopy != value))
				{
					this._DisplayCopy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TermsAndConditionsURL", DbType="NVarChar(MAX)")]
		public string TermsAndConditionsURL
		{
			get
			{
				return this._TermsAndConditionsURL;
			}
			set
			{
				if ((this._TermsAndConditionsURL != value))
				{
					this._TermsAndConditionsURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackgroundURL", DbType="NVarChar(MAX)")]
		public string BackgroundURL
		{
			get
			{
				return this._BackgroundURL;
			}
			set
			{
				if ((this._BackgroundURL != value))
				{
					this._BackgroundURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeaturedImageURL", DbType="NVarChar(MAX)")]
		public string FeaturedImageURL
		{
			get
			{
				return this._FeaturedImageURL;
			}
			set
			{
				if ((this._FeaturedImageURL != value))
				{
					this._FeaturedImageURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanksTitle", DbType="NVarChar(100)")]
		public string ThanksTitle
		{
			get
			{
				return this._ThanksTitle;
			}
			set
			{
				if ((this._ThanksTitle != value))
				{
					this._ThanksTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanksMessage", DbType="NVarChar(MAX)")]
		public string ThanksMessage
		{
			get
			{
				return this._ThanksMessage;
			}
			set
			{
				if ((this._ThanksMessage != value))
				{
					this._ThanksMessage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
	}
	
	public partial class Competitions_GetByNameResult
	{
		
		private int _Id;
		
		private string _Name;
		
		private bool _IsActive;
		
		private bool _IsMembersOnly;
		
		private string _Audience;
		
		private bool _IsAnOffer;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private bool _PostalAddress;
		
		private bool _Postcode;
		
		private bool _PhoneNumber;
		
		private bool _EmailAddress;
		
		private bool _Newsletter;
		
		private string _DisplayTitle;
		
		private string _DisplayCopy;
		
		private string _TermsAndConditionsURL;
		
		private string _BackgroundURL;
		
		private string _FeaturedImageURL;
		
		private string _ThanksTitle;
		
		private string _ThanksMessage;
		
		private bool _IsDeleted;
		
		public Competitions_GetByNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMembersOnly", DbType="Bit NOT NULL")]
		public bool IsMembersOnly
		{
			get
			{
				return this._IsMembersOnly;
			}
			set
			{
				if ((this._IsMembersOnly != value))
				{
					this._IsMembersOnly = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Audience", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Audience
		{
			get
			{
				return this._Audience;
			}
			set
			{
				if ((this._Audience != value))
				{
					this._Audience = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAnOffer", DbType="Bit NOT NULL")]
		public bool IsAnOffer
		{
			get
			{
				return this._IsAnOffer;
			}
			set
			{
				if ((this._IsAnOffer != value))
				{
					this._IsAnOffer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalAddress", DbType="Bit NOT NULL")]
		public bool PostalAddress
		{
			get
			{
				return this._PostalAddress;
			}
			set
			{
				if ((this._PostalAddress != value))
				{
					this._PostalAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="Bit NOT NULL")]
		public bool Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this._Postcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="Bit NOT NULL")]
		public bool PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="Bit NOT NULL")]
		public bool EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Newsletter", DbType="Bit NOT NULL")]
		public bool Newsletter
		{
			get
			{
				return this._Newsletter;
			}
			set
			{
				if ((this._Newsletter != value))
				{
					this._Newsletter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayTitle", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DisplayTitle
		{
			get
			{
				return this._DisplayTitle;
			}
			set
			{
				if ((this._DisplayTitle != value))
				{
					this._DisplayTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayCopy", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DisplayCopy
		{
			get
			{
				return this._DisplayCopy;
			}
			set
			{
				if ((this._DisplayCopy != value))
				{
					this._DisplayCopy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TermsAndConditionsURL", DbType="NVarChar(MAX)")]
		public string TermsAndConditionsURL
		{
			get
			{
				return this._TermsAndConditionsURL;
			}
			set
			{
				if ((this._TermsAndConditionsURL != value))
				{
					this._TermsAndConditionsURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackgroundURL", DbType="NVarChar(MAX)")]
		public string BackgroundURL
		{
			get
			{
				return this._BackgroundURL;
			}
			set
			{
				if ((this._BackgroundURL != value))
				{
					this._BackgroundURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeaturedImageURL", DbType="NVarChar(MAX)")]
		public string FeaturedImageURL
		{
			get
			{
				return this._FeaturedImageURL;
			}
			set
			{
				if ((this._FeaturedImageURL != value))
				{
					this._FeaturedImageURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanksTitle", DbType="NVarChar(100)")]
		public string ThanksTitle
		{
			get
			{
				return this._ThanksTitle;
			}
			set
			{
				if ((this._ThanksTitle != value))
				{
					this._ThanksTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanksMessage", DbType="NVarChar(MAX)")]
		public string ThanksMessage
		{
			get
			{
				return this._ThanksMessage;
			}
			set
			{
				if ((this._ThanksMessage != value))
				{
					this._ThanksMessage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
	}
	
	public partial class Competitions_Questions_GetByCompetitionIdResult
	{
		
		private int _Id;
		
		private int _CompetitionId;
		
		private string _Question;
		
		private bool _IsBool;
		
		private bool _Required;
		
		public Competitions_Questions_GetByCompetitionIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompetitionId", DbType="Int NOT NULL")]
		public int CompetitionId
		{
			get
			{
				return this._CompetitionId;
			}
			set
			{
				if ((this._CompetitionId != value))
				{
					this._CompetitionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this._Question = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBool", DbType="Bit NOT NULL")]
		public bool IsBool
		{
			get
			{
				return this._IsBool;
			}
			set
			{
				if ((this._IsBool != value))
				{
					this._IsBool = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Required", DbType="Bit NOT NULL")]
		public bool Required
		{
			get
			{
				return this._Required;
			}
			set
			{
				if ((this._Required != value))
				{
					this._Required = value;
				}
			}
		}
	}
	
	public partial class Competitions_Questions_GetByIdResult
	{
		
		private int _Id;
		
		private int _CompetitionId;
		
		private string _Question;
		
		private bool _IsBool;
		
		private bool _Required;
		
		public Competitions_Questions_GetByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompetitionId", DbType="Int NOT NULL")]
		public int CompetitionId
		{
			get
			{
				return this._CompetitionId;
			}
			set
			{
				if ((this._CompetitionId != value))
				{
					this._CompetitionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this._Question = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBool", DbType="Bit NOT NULL")]
		public bool IsBool
		{
			get
			{
				return this._IsBool;
			}
			set
			{
				if ((this._IsBool != value))
				{
					this._IsBool = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Required", DbType="Bit NOT NULL")]
		public bool Required
		{
			get
			{
				return this._Required;
			}
			set
			{
				if ((this._Required != value))
				{
					this._Required = value;
				}
			}
		}
	}
	
	public partial class Competitions_UpdateResult
	{
		
		private System.Nullable<decimal> _Column1;
		
		public Competitions_UpdateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class Competitions_Entries_Add_TMPResult
	{
		
		private string _Error;
		
		public Competitions_Entries_Add_TMPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="NVarChar(4000)")]
		public string Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this._Error = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
