#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoWebsites.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NgageCms")]
	public partial class NgageDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPageToTree(PageToTree instance);
    partial void UpdatePageToTree(PageToTree instance);
    partial void DeletePageToTree(PageToTree instance);
    partial void InsertUrlAlia(UrlAlia instance);
    partial void UpdateUrlAlia(UrlAlia instance);
    partial void DeleteUrlAlia(UrlAlia instance);
    #endregion
		
		public NgageDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NgageCmsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NgageDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NgageDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NgageDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NgageDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PageToTree> PageToTrees
		{
			get
			{
				return this.GetTable<PageToTree>();
			}
		}
		
		public System.Data.Linq.Table<UrlAlia> UrlAlias
		{
			get
			{
				return this.GetTable<UrlAlia>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ngage_Pages_SelectCurrentRevision_ByTreeId")]
		public ISingleResult<ngage_Pages_SelectCurrentRevision_ByTreeIdResult> ngage_Pages_SelectCurrentRevision_ByTreeId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TreeId", DbType="BigInt")] System.Nullable<long> treeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPreview", DbType="Bit")] System.Nullable<bool> isPreview, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageId", DbType="BigInt")] System.Nullable<long> languageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), treeId, isPreview, languageId);
			return ((ISingleResult<ngage_Pages_SelectCurrentRevision_ByTreeIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UrlAlias_Select_ByTreeId")]
		public ISingleResult<UrlAlias_Select_ByTreeIdResult> UrlAlias_Select_ByTreeId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TreeId", DbType="BigInt")] System.Nullable<long> treeId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), treeId);
			return ((ISingleResult<UrlAlias_Select_ByTreeIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ngage_MetaDataItems_SelectByTreeId")]
		public ISingleResult<ngage_MetaDataItems_SelectByTreeIdResult> ngage_MetaDataItems_SelectByTreeId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TreeId", DbType="BigInt")] System.Nullable<long> treeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPreview", DbType="Bit")] System.Nullable<bool> isPreview)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), treeId, isPreview);
			return ((ISingleResult<ngage_MetaDataItems_SelectByTreeIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ngage_Pages_SelectChildrenCurrentRevision_ByTreeId")]
		public ISingleResult<ngage_Pages_SelectChildrenCurrentRevision_ByTreeIdResult> ngage_Pages_SelectChildrenCurrentRevision_ByTreeId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TreeId", DbType="BigInt")] System.Nullable<long> treeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPreview", DbType="Bit")] System.Nullable<bool> isPreview, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemIndex", DbType="Int")] System.Nullable<int> itemIndex, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemCount", DbType="Int")] System.Nullable<int> itemCount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TagList", DbType="VarChar(2048)")] string tagList, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ArchiveDate", DbType="DateTime")] System.Nullable<System.DateTime> archiveDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageId", DbType="BigInt")] System.Nullable<long> languageId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderBy", DbType="NVarChar(30)")] string orderBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), treeId, isPreview, itemIndex, itemCount, tagList, archiveDate, languageId, orderBy);
			return ((ISingleResult<ngage_Pages_SelectChildrenCurrentRevision_ByTreeIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ngage_Assets_ByParentTreeId")]
		public ISingleResult<ngage_Assets_ByParentTreeIdResult> ngage_Assets_ByParentTreeId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TreeIdList", DbType="VarChar(1024)")] string treeIdList, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemIndex", DbType="Int")] System.Nullable<int> itemIndex, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemCount", DbType="Int")] System.Nullable<int> itemCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), treeIdList, itemIndex, itemCount);
			return ((ISingleResult<ngage_Assets_ByParentTreeIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ngage_UrlAlias_Select_Url")]
		public ISingleResult<ngage_UrlAlias_Select_UrlResult> ngage_UrlAlias_Select_Url([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Url", DbType="NVarChar(2048)")] string url, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPreview", DbType="Bit")] System.Nullable<bool> isPreview, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SiteId", DbType="BigInt")] System.Nullable<long> siteId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageId", DbType="BigInt")] System.Nullable<long> languageId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsMvcSite", DbType="Bit")] System.Nullable<bool> isMvcSite)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), url, isPreview, siteId, languageId, isMvcSite);
			return ((ISingleResult<ngage_UrlAlias_Select_UrlResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ngage_Asset_SelectByTreeId")]
		public ISingleResult<ngage_Asset_SelectByTreeIdResult> ngage_Asset_SelectByTreeId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TreeId", DbType="BigInt")] System.Nullable<long> treeId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), treeId);
			return ((ISingleResult<ngage_Asset_SelectByTreeIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Pages_Select_ByPageName")]
		public ISingleResult<Pages_Select_ByPageNameResult> Pages_Select_ByPageName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageName", DbType="NVarChar(100)")] string pageName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentId", DbType="BigInt")] System.Nullable<long> parentId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageName, parentId);
			return ((ISingleResult<Pages_Select_ByPageNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Pages_Select_ById")]
		public ISingleResult<Pages_Select_ByIdResult> Pages_Select_ById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<Pages_Select_ByIdResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PageToTree")]
	public partial class PageToTree : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private long _PageId;
		
		private long _TreeId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnPageIdChanging(long value);
    partial void OnPageIdChanged();
    partial void OnTreeIdChanging(long value);
    partial void OnTreeIdChanged();
    #endregion
		
		public PageToTree()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageId", DbType="BigInt NOT NULL")]
		public long PageId
		{
			get
			{
				return this._PageId;
			}
			set
			{
				if ((this._PageId != value))
				{
					this.OnPageIdChanging(value);
					this.SendPropertyChanging();
					this._PageId = value;
					this.SendPropertyChanged("PageId");
					this.OnPageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreeId", DbType="BigInt NOT NULL")]
		public long TreeId
		{
			get
			{
				return this._TreeId;
			}
			set
			{
				if ((this._TreeId != value))
				{
					this.OnTreeIdChanging(value);
					this.SendPropertyChanging();
					this._TreeId = value;
					this.SendPropertyChanged("TreeId");
					this.OnTreeIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UrlAlias")]
	public partial class UrlAlia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _AliasUrl;
		
		private bool _IsPrimary;
		
		private long _TreeId;
		
		private System.Nullable<long> _SiteId;
		
		private System.DateTime _DateCreated;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnAliasUrlChanging(string value);
    partial void OnAliasUrlChanged();
    partial void OnIsPrimaryChanging(bool value);
    partial void OnIsPrimaryChanged();
    partial void OnTreeIdChanging(long value);
    partial void OnTreeIdChanged();
    partial void OnSiteIdChanging(System.Nullable<long> value);
    partial void OnSiteIdChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    #endregion
		
		public UrlAlia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AliasUrl", DbType="VarChar(1024)")]
		public string AliasUrl
		{
			get
			{
				return this._AliasUrl;
			}
			set
			{
				if ((this._AliasUrl != value))
				{
					this.OnAliasUrlChanging(value);
					this.SendPropertyChanging();
					this._AliasUrl = value;
					this.SendPropertyChanged("AliasUrl");
					this.OnAliasUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrimary", DbType="Bit NOT NULL")]
		public bool IsPrimary
		{
			get
			{
				return this._IsPrimary;
			}
			set
			{
				if ((this._IsPrimary != value))
				{
					this.OnIsPrimaryChanging(value);
					this.SendPropertyChanging();
					this._IsPrimary = value;
					this.SendPropertyChanged("IsPrimary");
					this.OnIsPrimaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreeId", DbType="BigInt NOT NULL")]
		public long TreeId
		{
			get
			{
				return this._TreeId;
			}
			set
			{
				if ((this._TreeId != value))
				{
					this.OnTreeIdChanging(value);
					this.SendPropertyChanging();
					this._TreeId = value;
					this.SendPropertyChanged("TreeId");
					this.OnTreeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteId", DbType="BigInt")]
		public System.Nullable<long> SiteId
		{
			get
			{
				return this._SiteId;
			}
			set
			{
				if ((this._SiteId != value))
				{
					this.OnSiteIdChanging(value);
					this.SendPropertyChanging();
					this._SiteId = value;
					this.SendPropertyChanged("SiteId");
					this.OnSiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class ngage_Pages_SelectCurrentRevision_ByTreeIdResult
	{
		
		private long _RevisionId;
		
		private System.Nullable<long> _PageId;
		
		private string _Content;
		
		private System.Nullable<System.DateTime> _PublishStartDate;
		
		private System.Nullable<System.DateTime> _PublishEndDate;
		
		private string _TemplateType;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private string _CreatedBy;
		
		private string _Teaser;
		
		private string _Title;
		
		private string _DisplayTitle;
		
		private string _PageTemplate;
		
		private string _MetaTitle;
		
		private string _MetaDescription;
		
		private bool _IsMembersOnly;
		
		private string _MasterPageFile;
		
		private string _AliasUrl;
		
		private System.Nullable<long> _RootTreeId;
		
		private string _CanonicalUrl;
		
		private long _TreeId;
		
		private System.Nullable<double> _Ordinal;
		
		private System.Nullable<System.DateTime> _DateModified;
		
		private System.Nullable<long> _AssetTreeId;
		
		private long _ParentTreeId;
		
		public ngage_Pages_SelectCurrentRevision_ByTreeIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RevisionId", DbType="BigInt NOT NULL")]
		public long RevisionId
		{
			get
			{
				return this._RevisionId;
			}
			set
			{
				if ((this._RevisionId != value))
				{
					this._RevisionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageId", DbType="BigInt")]
		public System.Nullable<long> PageId
		{
			get
			{
				return this._PageId;
			}
			set
			{
				if ((this._PageId != value))
				{
					this._PageId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="VarChar(MAX)")]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this._Content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishStartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PublishStartDate
		{
			get
			{
				return this._PublishStartDate;
			}
			set
			{
				if ((this._PublishStartDate != value))
				{
					this._PublishStartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishEndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PublishEndDate
		{
			get
			{
				return this._PublishEndDate;
			}
			set
			{
				if ((this._PublishEndDate != value))
				{
					this._PublishEndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TemplateType
		{
			get
			{
				return this._TemplateType;
			}
			set
			{
				if ((this._TemplateType != value))
				{
					this._TemplateType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(150)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teaser", DbType="VarChar(MAX)")]
		public string Teaser
		{
			get
			{
				return this._Teaser;
			}
			set
			{
				if ((this._Teaser != value))
				{
					this._Teaser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(100)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayTitle", DbType="VarChar(200)")]
		public string DisplayTitle
		{
			get
			{
				return this._DisplayTitle;
			}
			set
			{
				if ((this._DisplayTitle != value))
				{
					this._DisplayTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageTemplate", DbType="VarChar(250)")]
		public string PageTemplate
		{
			get
			{
				return this._PageTemplate;
			}
			set
			{
				if ((this._PageTemplate != value))
				{
					this._PageTemplate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaTitle", DbType="VarChar(150)")]
		public string MetaTitle
		{
			get
			{
				return this._MetaTitle;
			}
			set
			{
				if ((this._MetaTitle != value))
				{
					this._MetaTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaDescription", DbType="VarChar(300)")]
		public string MetaDescription
		{
			get
			{
				return this._MetaDescription;
			}
			set
			{
				if ((this._MetaDescription != value))
				{
					this._MetaDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMembersOnly", DbType="Bit NOT NULL")]
		public bool IsMembersOnly
		{
			get
			{
				return this._IsMembersOnly;
			}
			set
			{
				if ((this._IsMembersOnly != value))
				{
					this._IsMembersOnly = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterPageFile", DbType="NVarChar(50)")]
		public string MasterPageFile
		{
			get
			{
				return this._MasterPageFile;
			}
			set
			{
				if ((this._MasterPageFile != value))
				{
					this._MasterPageFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AliasUrl", DbType="VarChar(1024)")]
		public string AliasUrl
		{
			get
			{
				return this._AliasUrl;
			}
			set
			{
				if ((this._AliasUrl != value))
				{
					this._AliasUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RootTreeId", DbType="BigInt")]
		public System.Nullable<long> RootTreeId
		{
			get
			{
				return this._RootTreeId;
			}
			set
			{
				if ((this._RootTreeId != value))
				{
					this._RootTreeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanonicalUrl", DbType="VarChar(1024)")]
		public string CanonicalUrl
		{
			get
			{
				return this._CanonicalUrl;
			}
			set
			{
				if ((this._CanonicalUrl != value))
				{
					this._CanonicalUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreeId", DbType="BigInt NOT NULL")]
		public long TreeId
		{
			get
			{
				return this._TreeId;
			}
			set
			{
				if ((this._TreeId != value))
				{
					this._TreeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ordinal", DbType="Float")]
		public System.Nullable<double> Ordinal
		{
			get
			{
				return this._Ordinal;
			}
			set
			{
				if ((this._Ordinal != value))
				{
					this._Ordinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this._DateModified = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssetTreeId", DbType="BigInt")]
		public System.Nullable<long> AssetTreeId
		{
			get
			{
				return this._AssetTreeId;
			}
			set
			{
				if ((this._AssetTreeId != value))
				{
					this._AssetTreeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentTreeId", DbType="BigInt NOT NULL")]
		public long ParentTreeId
		{
			get
			{
				return this._ParentTreeId;
			}
			set
			{
				if ((this._ParentTreeId != value))
				{
					this._ParentTreeId = value;
				}
			}
		}
	}
	
	public partial class UrlAlias_Select_ByTreeIdResult
	{
		
		private long _Id;
		
		private string _AliasUrl;
		
		private long _TreeId;
		
		private bool _IsPrimary;
		
		private System.DateTime _DateCreated;
		
		public UrlAlias_Select_ByTreeIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AliasUrl", DbType="VarChar(1024)")]
		public string AliasUrl
		{
			get
			{
				return this._AliasUrl;
			}
			set
			{
				if ((this._AliasUrl != value))
				{
					this._AliasUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreeId", DbType="BigInt NOT NULL")]
		public long TreeId
		{
			get
			{
				return this._TreeId;
			}
			set
			{
				if ((this._TreeId != value))
				{
					this._TreeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrimary", DbType="Bit NOT NULL")]
		public bool IsPrimary
		{
			get
			{
				return this._IsPrimary;
			}
			set
			{
				if ((this._IsPrimary != value))
				{
					this._IsPrimary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
	}
	
	public partial class ngage_MetaDataItems_SelectByTreeIdResult
	{
		
		private long _MetaItemId;
		
		private string _MetaValue;
		
		private string _DataValue;
		
		private string _DataType;
		
		private string _MetaDataName;
		
		private string _HtmlValue;
		
		private string _MetaDisplayLabel;
		
		private System.Nullable<long> _TreeId;
		
		private System.Nullable<System.DateTime> _DateModified;
		
		public ngage_MetaDataItems_SelectByTreeIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaItemId", DbType="BigInt NOT NULL")]
		public long MetaItemId
		{
			get
			{
				return this._MetaItemId;
			}
			set
			{
				if ((this._MetaItemId != value))
				{
					this._MetaItemId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaValue", DbType="VarChar(MAX)")]
		public string MetaValue
		{
			get
			{
				return this._MetaValue;
			}
			set
			{
				if ((this._MetaValue != value))
				{
					this._MetaValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataValue", DbType="VarChar(MAX)")]
		public string DataValue
		{
			get
			{
				return this._DataValue;
			}
			set
			{
				if ((this._DataValue != value))
				{
					this._DataValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataType", DbType="VarChar(20)")]
		public string DataType
		{
			get
			{
				return this._DataType;
			}
			set
			{
				if ((this._DataType != value))
				{
					this._DataType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaDataName", DbType="VarChar(8000)")]
		public string MetaDataName
		{
			get
			{
				return this._MetaDataName;
			}
			set
			{
				if ((this._MetaDataName != value))
				{
					this._MetaDataName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HtmlValue", DbType="VarChar(MAX)")]
		public string HtmlValue
		{
			get
			{
				return this._HtmlValue;
			}
			set
			{
				if ((this._HtmlValue != value))
				{
					this._HtmlValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaDisplayLabel", DbType="VarChar(50)")]
		public string MetaDisplayLabel
		{
			get
			{
				return this._MetaDisplayLabel;
			}
			set
			{
				if ((this._MetaDisplayLabel != value))
				{
					this._MetaDisplayLabel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreeId", DbType="BigInt")]
		public System.Nullable<long> TreeId
		{
			get
			{
				return this._TreeId;
			}
			set
			{
				if ((this._TreeId != value))
				{
					this._TreeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this._DateModified = value;
				}
			}
		}
	}
	
	public partial class ngage_Pages_SelectChildrenCurrentRevision_ByTreeIdResult
	{
		
		private System.Nullable<long> _RevisionId;
		
		private System.Nullable<long> _PageId;
		
		private string _Content;
		
		private System.Nullable<System.DateTime> _PublishStartDate;
		
		private System.Nullable<System.DateTime> _PublishEndDate;
		
		private string _TemplateType;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private string _CreatedBy;
		
		private string _Teaser;
		
		private string _Title;
		
		private string _DisplayTitle;
		
		private string _PageTemplate;
		
		private string _MetaTitle;
		
		private string _MetaDescription;
		
		private System.Nullable<bool> _IsMembersOnly;
		
		private string _MasterPageFile;
		
		private string _AliasUrl;
		
		private System.Nullable<long> _RootTreeId;
		
		private string _CanonicalUrl;
		
		private System.Nullable<long> _TreeId;
		
		private System.Nullable<double> _Ordinal;
		
		private System.Nullable<System.DateTime> _DateModified;
		
		private System.Nullable<long> _AssetTreeId;
		
		private System.Nullable<long> _ParentTreeId;
		
		private System.Nullable<int> _ItemCount;
		
		public ngage_Pages_SelectChildrenCurrentRevision_ByTreeIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RevisionId", DbType="BigInt")]
		public System.Nullable<long> RevisionId
		{
			get
			{
				return this._RevisionId;
			}
			set
			{
				if ((this._RevisionId != value))
				{
					this._RevisionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageId", DbType="BigInt")]
		public System.Nullable<long> PageId
		{
			get
			{
				return this._PageId;
			}
			set
			{
				if ((this._PageId != value))
				{
					this._PageId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NVarChar(MAX)")]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this._Content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishStartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PublishStartDate
		{
			get
			{
				return this._PublishStartDate;
			}
			set
			{
				if ((this._PublishStartDate != value))
				{
					this._PublishStartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishEndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PublishEndDate
		{
			get
			{
				return this._PublishEndDate;
			}
			set
			{
				if ((this._PublishEndDate != value))
				{
					this._PublishEndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateType", DbType="NVarChar(50)")]
		public string TemplateType
		{
			get
			{
				return this._TemplateType;
			}
			set
			{
				if ((this._TemplateType != value))
				{
					this._TemplateType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(150)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teaser", DbType="NVarChar(MAX)")]
		public string Teaser
		{
			get
			{
				return this._Teaser;
			}
			set
			{
				if ((this._Teaser != value))
				{
					this._Teaser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayTitle", DbType="NVarChar(100)")]
		public string DisplayTitle
		{
			get
			{
				return this._DisplayTitle;
			}
			set
			{
				if ((this._DisplayTitle != value))
				{
					this._DisplayTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageTemplate", DbType="NVarChar(250)")]
		public string PageTemplate
		{
			get
			{
				return this._PageTemplate;
			}
			set
			{
				if ((this._PageTemplate != value))
				{
					this._PageTemplate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaTitle", DbType="NVarChar(150)")]
		public string MetaTitle
		{
			get
			{
				return this._MetaTitle;
			}
			set
			{
				if ((this._MetaTitle != value))
				{
					this._MetaTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaDescription", DbType="NVarChar(300)")]
		public string MetaDescription
		{
			get
			{
				return this._MetaDescription;
			}
			set
			{
				if ((this._MetaDescription != value))
				{
					this._MetaDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMembersOnly", DbType="Bit")]
		public System.Nullable<bool> IsMembersOnly
		{
			get
			{
				return this._IsMembersOnly;
			}
			set
			{
				if ((this._IsMembersOnly != value))
				{
					this._IsMembersOnly = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterPageFile", DbType="NVarChar(50)")]
		public string MasterPageFile
		{
			get
			{
				return this._MasterPageFile;
			}
			set
			{
				if ((this._MasterPageFile != value))
				{
					this._MasterPageFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AliasUrl", DbType="NVarChar(1024)")]
		public string AliasUrl
		{
			get
			{
				return this._AliasUrl;
			}
			set
			{
				if ((this._AliasUrl != value))
				{
					this._AliasUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RootTreeId", DbType="BigInt")]
		public System.Nullable<long> RootTreeId
		{
			get
			{
				return this._RootTreeId;
			}
			set
			{
				if ((this._RootTreeId != value))
				{
					this._RootTreeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanonicalUrl", DbType="NVarChar(1024)")]
		public string CanonicalUrl
		{
			get
			{
				return this._CanonicalUrl;
			}
			set
			{
				if ((this._CanonicalUrl != value))
				{
					this._CanonicalUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreeId", DbType="BigInt")]
		public System.Nullable<long> TreeId
		{
			get
			{
				return this._TreeId;
			}
			set
			{
				if ((this._TreeId != value))
				{
					this._TreeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ordinal", DbType="Float")]
		public System.Nullable<double> Ordinal
		{
			get
			{
				return this._Ordinal;
			}
			set
			{
				if ((this._Ordinal != value))
				{
					this._Ordinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this._DateModified = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssetTreeId", DbType="BigInt")]
		public System.Nullable<long> AssetTreeId
		{
			get
			{
				return this._AssetTreeId;
			}
			set
			{
				if ((this._AssetTreeId != value))
				{
					this._AssetTreeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentTreeId", DbType="BigInt")]
		public System.Nullable<long> ParentTreeId
		{
			get
			{
				return this._ParentTreeId;
			}
			set
			{
				if ((this._ParentTreeId != value))
				{
					this._ParentTreeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCount", DbType="Int")]
		public System.Nullable<int> ItemCount
		{
			get
			{
				return this._ItemCount;
			}
			set
			{
				if ((this._ItemCount != value))
				{
					this._ItemCount = value;
				}
			}
		}
	}
	
	public partial class ngage_Assets_ByParentTreeIdResult
	{
		
		private System.Nullable<long> _TreeId;
		
		private System.Nullable<long> _ParentTreeId;
		
		private System.Nullable<bool> _IsFolder;
		
		private string _DisplayName;
		
		private string _Description;
		
		private System.Nullable<long> _AssetId;
		
		private string _NavigateUrl;
		
		private System.Nullable<double> _Ordinal;
		
		private string _AliasUrl;
		
		private System.Nullable<System.DateTime> _DateModified;
		
		private string _FileName;
		
		private string _FolderLocation;
		
		private System.Nullable<bool> _IsAssignedOnly;
		
		private System.Nullable<bool> _IsMembersOnly;
		
		private string _OriginalFileName;
		
		private System.Nullable<bool> _ThumbnailIsDifferent;
		
		private System.Nullable<long> _AssetsTypeId;
		
		private System.Nullable<long> _AssetIconTreeId;
		
		private System.Nullable<int> _ItemCount;
		
		public ngage_Assets_ByParentTreeIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreeId", DbType="BigInt")]
		public System.Nullable<long> TreeId
		{
			get
			{
				return this._TreeId;
			}
			set
			{
				if ((this._TreeId != value))
				{
					this._TreeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentTreeId", DbType="BigInt")]
		public System.Nullable<long> ParentTreeId
		{
			get
			{
				return this._ParentTreeId;
			}
			set
			{
				if ((this._ParentTreeId != value))
				{
					this._ParentTreeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFolder", DbType="Bit")]
		public System.Nullable<bool> IsFolder
		{
			get
			{
				return this._IsFolder;
			}
			set
			{
				if ((this._IsFolder != value))
				{
					this._IsFolder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayName", DbType="NVarChar(100)")]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this._DisplayName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(2048)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssetId", DbType="BigInt")]
		public System.Nullable<long> AssetId
		{
			get
			{
				return this._AssetId;
			}
			set
			{
				if ((this._AssetId != value))
				{
					this._AssetId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NavigateUrl", DbType="NVarChar(1024)")]
		public string NavigateUrl
		{
			get
			{
				return this._NavigateUrl;
			}
			set
			{
				if ((this._NavigateUrl != value))
				{
					this._NavigateUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ordinal", DbType="Float")]
		public System.Nullable<double> Ordinal
		{
			get
			{
				return this._Ordinal;
			}
			set
			{
				if ((this._Ordinal != value))
				{
					this._Ordinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AliasUrl", DbType="NVarChar(1024)")]
		public string AliasUrl
		{
			get
			{
				return this._AliasUrl;
			}
			set
			{
				if ((this._AliasUrl != value))
				{
					this._AliasUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this._DateModified = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(100)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderLocation", DbType="NVarChar(1024)")]
		public string FolderLocation
		{
			get
			{
				return this._FolderLocation;
			}
			set
			{
				if ((this._FolderLocation != value))
				{
					this._FolderLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAssignedOnly", DbType="Bit")]
		public System.Nullable<bool> IsAssignedOnly
		{
			get
			{
				return this._IsAssignedOnly;
			}
			set
			{
				if ((this._IsAssignedOnly != value))
				{
					this._IsAssignedOnly = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMembersOnly", DbType="Bit")]
		public System.Nullable<bool> IsMembersOnly
		{
			get
			{
				return this._IsMembersOnly;
			}
			set
			{
				if ((this._IsMembersOnly != value))
				{
					this._IsMembersOnly = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalFileName", DbType="NVarChar(100)")]
		public string OriginalFileName
		{
			get
			{
				return this._OriginalFileName;
			}
			set
			{
				if ((this._OriginalFileName != value))
				{
					this._OriginalFileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThumbnailIsDifferent", DbType="Bit")]
		public System.Nullable<bool> ThumbnailIsDifferent
		{
			get
			{
				return this._ThumbnailIsDifferent;
			}
			set
			{
				if ((this._ThumbnailIsDifferent != value))
				{
					this._ThumbnailIsDifferent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssetsTypeId", DbType="BigInt")]
		public System.Nullable<long> AssetsTypeId
		{
			get
			{
				return this._AssetsTypeId;
			}
			set
			{
				if ((this._AssetsTypeId != value))
				{
					this._AssetsTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssetIconTreeId", DbType="BigInt")]
		public System.Nullable<long> AssetIconTreeId
		{
			get
			{
				return this._AssetIconTreeId;
			}
			set
			{
				if ((this._AssetIconTreeId != value))
				{
					this._AssetIconTreeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCount", DbType="Int")]
		public System.Nullable<int> ItemCount
		{
			get
			{
				return this._ItemCount;
			}
			set
			{
				if ((this._ItemCount != value))
				{
					this._ItemCount = value;
				}
			}
		}
	}
	
	public partial class ngage_UrlAlias_Select_UrlResult
	{
		
		private System.Nullable<long> _TreeId;
		
		private System.Nullable<bool> _IsPrimaryAlias;
		
		private string _PrimaryUrlAlias;
		
		private System.Nullable<System.DateTime> _DateModified;
		
		private string _MvcUrl;
		
		private string _FileLocation;
		
		public ngage_UrlAlias_Select_UrlResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreeId", DbType="BigInt")]
		public System.Nullable<long> TreeId
		{
			get
			{
				return this._TreeId;
			}
			set
			{
				if ((this._TreeId != value))
				{
					this._TreeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrimaryAlias", DbType="Bit")]
		public System.Nullable<bool> IsPrimaryAlias
		{
			get
			{
				return this._IsPrimaryAlias;
			}
			set
			{
				if ((this._IsPrimaryAlias != value))
				{
					this._IsPrimaryAlias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryUrlAlias", DbType="NVarChar(1024)")]
		public string PrimaryUrlAlias
		{
			get
			{
				return this._PrimaryUrlAlias;
			}
			set
			{
				if ((this._PrimaryUrlAlias != value))
				{
					this._PrimaryUrlAlias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this._DateModified = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MvcUrl", DbType="NVarChar(2048)")]
		public string MvcUrl
		{
			get
			{
				return this._MvcUrl;
			}
			set
			{
				if ((this._MvcUrl != value))
				{
					this._MvcUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileLocation", DbType="NVarChar(1024)")]
		public string FileLocation
		{
			get
			{
				return this._FileLocation;
			}
			set
			{
				if ((this._FileLocation != value))
				{
					this._FileLocation = value;
				}
			}
		}
	}
	
	public partial class ngage_Asset_SelectByTreeIdResult
	{
		
		private long _AssetId;
		
		private string _OriginalFileName;
		
		private string _FileName;
		
		private bool _IsMembersOnly;
		
		private bool _IsAssignedOnly;
		
		private string _TreeTitle;
		
		private string _FolderLocation;
		
		private long _ParentTreeId;
		
		private string _Description;
		
		private string _DisplayName;
		
		private bool _ThumbnailIsDifferent;
		
		private long _TreeId;
		
		private System.Nullable<System.DateTime> _DateModified;
		
		private string _AliasUrl;
		
		private bool _IsFolder;
		
		private string _NavigateUrl;
		
		private System.Nullable<double> _Ordinal;
		
		private long _AssetsTypeId;
		
		private long _AssetIconTreeId;
		
		public ngage_Asset_SelectByTreeIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssetId", DbType="BigInt NOT NULL")]
		public long AssetId
		{
			get
			{
				return this._AssetId;
			}
			set
			{
				if ((this._AssetId != value))
				{
					this._AssetId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalFileName", DbType="VarChar(100)")]
		public string OriginalFileName
		{
			get
			{
				return this._OriginalFileName;
			}
			set
			{
				if ((this._OriginalFileName != value))
				{
					this._OriginalFileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(8000)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMembersOnly", DbType="Bit NOT NULL")]
		public bool IsMembersOnly
		{
			get
			{
				return this._IsMembersOnly;
			}
			set
			{
				if ((this._IsMembersOnly != value))
				{
					this._IsMembersOnly = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAssignedOnly", DbType="Bit NOT NULL")]
		public bool IsAssignedOnly
		{
			get
			{
				return this._IsAssignedOnly;
			}
			set
			{
				if ((this._IsAssignedOnly != value))
				{
					this._IsAssignedOnly = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreeTitle", DbType="VarChar(100)")]
		public string TreeTitle
		{
			get
			{
				return this._TreeTitle;
			}
			set
			{
				if ((this._TreeTitle != value))
				{
					this._TreeTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderLocation", DbType="VarChar(1024)")]
		public string FolderLocation
		{
			get
			{
				return this._FolderLocation;
			}
			set
			{
				if ((this._FolderLocation != value))
				{
					this._FolderLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentTreeId", DbType="BigInt NOT NULL")]
		public long ParentTreeId
		{
			get
			{
				return this._ParentTreeId;
			}
			set
			{
				if ((this._ParentTreeId != value))
				{
					this._ParentTreeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(2048)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayName", DbType="VarChar(100)")]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this._DisplayName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThumbnailIsDifferent", DbType="Bit NOT NULL")]
		public bool ThumbnailIsDifferent
		{
			get
			{
				return this._ThumbnailIsDifferent;
			}
			set
			{
				if ((this._ThumbnailIsDifferent != value))
				{
					this._ThumbnailIsDifferent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreeId", DbType="BigInt NOT NULL")]
		public long TreeId
		{
			get
			{
				return this._TreeId;
			}
			set
			{
				if ((this._TreeId != value))
				{
					this._TreeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this._DateModified = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AliasUrl", DbType="VarChar(1024)")]
		public string AliasUrl
		{
			get
			{
				return this._AliasUrl;
			}
			set
			{
				if ((this._AliasUrl != value))
				{
					this._AliasUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFolder", DbType="Bit NOT NULL")]
		public bool IsFolder
		{
			get
			{
				return this._IsFolder;
			}
			set
			{
				if ((this._IsFolder != value))
				{
					this._IsFolder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NavigateUrl", DbType="VarChar(1024)")]
		public string NavigateUrl
		{
			get
			{
				return this._NavigateUrl;
			}
			set
			{
				if ((this._NavigateUrl != value))
				{
					this._NavigateUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ordinal", DbType="Float")]
		public System.Nullable<double> Ordinal
		{
			get
			{
				return this._Ordinal;
			}
			set
			{
				if ((this._Ordinal != value))
				{
					this._Ordinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssetsTypeId", DbType="BigInt NOT NULL")]
		public long AssetsTypeId
		{
			get
			{
				return this._AssetsTypeId;
			}
			set
			{
				if ((this._AssetsTypeId != value))
				{
					this._AssetsTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssetIconTreeId", DbType="BigInt NOT NULL")]
		public long AssetIconTreeId
		{
			get
			{
				return this._AssetIconTreeId;
			}
			set
			{
				if ((this._AssetIconTreeId != value))
				{
					this._AssetIconTreeId = value;
				}
			}
		}
	}
	
	public partial class Pages_Select_ByPageNameResult
	{
		
		private long _Id;
		
		private string _Title;
		
		private bool _IsActive;
		
		private bool _IsSearchable;
		
		private System.Nullable<System.DateTime> _DisplayDate;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private long _TreeId;
		
		public Pages_Select_ByPageNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(100)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSearchable", DbType="Bit NOT NULL")]
		public bool IsSearchable
		{
			get
			{
				return this._IsSearchable;
			}
			set
			{
				if ((this._IsSearchable != value))
				{
					this._IsSearchable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DisplayDate
		{
			get
			{
				return this._DisplayDate;
			}
			set
			{
				if ((this._DisplayDate != value))
				{
					this._DisplayDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreeId", DbType="BigInt NOT NULL")]
		public long TreeId
		{
			get
			{
				return this._TreeId;
			}
			set
			{
				if ((this._TreeId != value))
				{
					this._TreeId = value;
				}
			}
		}
	}
	
	public partial class Pages_Select_ByIdResult
	{
		
		private long _Id;
		
		private string _Title;
		
		private bool _IsActive;
		
		private bool _IsSearchable;
		
		private bool _IsNavigation;
		
		private System.Nullable<System.DateTime> _DisplayDate;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private bool _IsMembersOnly;
		
		public Pages_Select_ByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(100)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSearchable", DbType="Bit NOT NULL")]
		public bool IsSearchable
		{
			get
			{
				return this._IsSearchable;
			}
			set
			{
				if ((this._IsSearchable != value))
				{
					this._IsSearchable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsNavigation", DbType="Bit NOT NULL")]
		public bool IsNavigation
		{
			get
			{
				return this._IsNavigation;
			}
			set
			{
				if ((this._IsNavigation != value))
				{
					this._IsNavigation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DisplayDate
		{
			get
			{
				return this._DisplayDate;
			}
			set
			{
				if ((this._DisplayDate != value))
				{
					this._DisplayDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMembersOnly", DbType="Bit NOT NULL")]
		public bool IsMembersOnly
		{
			get
			{
				return this._IsMembersOnly;
			}
			set
			{
				if ((this._IsMembersOnly != value))
				{
					this._IsMembersOnly = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
