#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoWebsites.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NFUWebMisc")]
	public partial class QuizDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public QuizDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NFUWebMiscConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuizDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuizDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuizDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuizDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Answers_GetByQuizId")]
		public ISingleResult<Quiz_Answers_GetByQuizIdResult> Quiz_Answers_GetByQuizId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuizId", DbType="Int")] System.Nullable<int> quizId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), quizId);
			return ((ISingleResult<Quiz_Answers_GetByQuizIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Sections_GetByQuizId")]
		public ISingleResult<Quiz_Sections_GetByQuizIdResult> Quiz_Sections_GetByQuizId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuizId", DbType="Int")] System.Nullable<int> quizId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), quizId);
			return ((ISingleResult<Quiz_Sections_GetByQuizIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Entries_GetByQuizId")]
		public ISingleResult<Quiz_Entries_GetByQuizIdResult> Quiz_Entries_GetByQuizId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuizId", DbType="Int")] System.Nullable<int> quizId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), quizId);
			return ((ISingleResult<Quiz_Entries_GetByQuizIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Results_GetByEntryId")]
		public ISingleResult<Quiz_Results_GetByEntryIdResult> Quiz_Results_GetByEntryId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryId", DbType="Int")] System.Nullable<int> entryId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), entryId);
			return ((ISingleResult<Quiz_Results_GetByEntryIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Options_GetById")]
		public ISingleResult<Quiz_Options_GetByIdResult> Quiz_Options_GetById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<Quiz_Options_GetByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Options_GetByQuestionId")]
		public ISingleResult<Quiz_Options_GetByQuestionIdResult> Quiz_Options_GetByQuestionId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuestionId", DbType="Int")] System.Nullable<int> questionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), questionId);
			return ((ISingleResult<Quiz_Options_GetByQuestionIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Questions_GetByQuizId")]
		public ISingleResult<Quiz_Questions_GetByQuizIdResult> Quiz_Questions_GetByQuizId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuizId", DbType="Int")] System.Nullable<int> quizId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), quizId);
			return ((ISingleResult<Quiz_Questions_GetByQuizIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Questions_GetBySectionId")]
		public ISingleResult<Quiz_Questions_GetBySectionIdResult> Quiz_Questions_GetBySectionId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SectionId", DbType="Int")] System.Nullable<int> sectionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sectionId);
			return ((ISingleResult<Quiz_Questions_GetBySectionIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Questions_GetById")]
		public ISingleResult<Quiz_Questions_GetByIdResult> Quiz_Questions_GetById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<Quiz_Questions_GetByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Entries_Insert")]
		public ISingleResult<Quiz_Entries_InsertResult> Quiz_Entries_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuizId", DbType="Int")] System.Nullable<int> quizId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Score", DbType="Decimal(18,1)")] System.Nullable<decimal> score)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), quizId, score);
			return ((ISingleResult<Quiz_Entries_InsertResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Results_Insert")]
		public ISingleResult<Quiz_Results_InsertResult> Quiz_Results_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryId", DbType="Int")] System.Nullable<int> entryId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OptionId", DbType="Int")] System.Nullable<int> optionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), entryId, optionId);
			return ((ISingleResult<Quiz_Results_InsertResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_GetAll")]
		public ISingleResult<Quiz_GetAllResult> Quiz_GetAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Quiz_GetAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_GetById")]
		public ISingleResult<Quiz_GetByIdResult> Quiz_GetById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<Quiz_GetByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Resources_GetById")]
		public ISingleResult<Quiz_Resources_GetByIdResult> Quiz_Resources_GetById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<Quiz_Resources_GetByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_RequiredResources_GetByQuizId")]
		public ISingleResult<Quiz_RequiredResources_GetByQuizIdResult> Quiz_RequiredResources_GetByQuizId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuizId", DbType="Int")] System.Nullable<int> quizId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), quizId);
			return ((ISingleResult<Quiz_RequiredResources_GetByQuizIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Options_Insert")]
		public int Quiz_Options_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuizId", DbType="Int")] System.Nullable<int> quizId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuestionId", DbType="Int")] System.Nullable<int> questionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="NVarChar(MAX)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResourceId", DbType="Int")] System.Nullable<int> resourceId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Score", DbType="Decimal(18,1)")] System.Nullable<decimal> score)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), quizId, questionId, title, resourceId, score);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Insert")]
		public ISingleResult<Quiz_InsertResult> Quiz_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="NVarChar(MAX)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Logo", DbType="NVarChar(MAX)")] string logo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BackgroundImage", DbType="NVarChar(MAX)")] string backgroundImage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Colours", DbType="NVarChar(MAX)")] string colours, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MinQuestionCount", DbType="Int")] System.Nullable<int> minQuestionCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), title, logo, description, backgroundImage, colours, minQuestionCount);
			return ((ISingleResult<Quiz_InsertResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Resources_Insert")]
		public ISingleResult<Quiz_Resources_InsertResult> Quiz_Resources_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="NVarChar(MAX)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Url", DbType="NVarChar(MAX)")] string url, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ImageUrl", DbType="NVarChar(MAX)")] string imageUrl)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), title, url, description, imageUrl);
			return ((ISingleResult<Quiz_Resources_InsertResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Sections_Insert")]
		public ISingleResult<Quiz_Sections_InsertResult> Quiz_Sections_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuizId", DbType="Int")] System.Nullable<int> quizId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="NVarChar(MAX)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MinQuestionCount", DbType="Int")] System.Nullable<int> minQuestionCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), quizId, title, description, minQuestionCount);
			return ((ISingleResult<Quiz_Sections_InsertResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Questions_Insert")]
		public ISingleResult<Quiz_Questions_InsertResult> Quiz_Questions_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuizId", DbType="Int")] System.Nullable<int> quizId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SectionId", DbType="NVarChar(MAX)")] string sectionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="NVarChar(MAX)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Alias", DbType="NVarChar(MAX)")] string alias, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BinaryAnswer", DbType="Bit")] System.Nullable<bool> binaryAnswer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaxScore", DbType="Decimal(18,1)")] System.Nullable<decimal> maxScore, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MinScore", DbType="Decimal(18,1)")] System.Nullable<decimal> minScore)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), quizId, sectionId, title, alias, description, binaryAnswer, maxScore, minScore);
			return ((ISingleResult<Quiz_Questions_InsertResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_RequiredResources_Insert")]
		public int Quiz_RequiredResources_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuizId", DbType="Int")] System.Nullable<int> quizId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResourceId", DbType="Int")] System.Nullable<int> resourceId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), quizId, resourceId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Delete")]
		public int Quiz_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Update")]
		public int Quiz_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="NVarChar(MAX)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Logo", DbType="NVarChar(MAX)")] string logo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BackgroundImage", DbType="NVarChar(MAX)")] string backgroundImage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Colours", DbType="NVarChar(MAX)")] string colours, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MinQuestionCount", DbType="Int")] System.Nullable<int> minQuestionCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, title, logo, description, backgroundImage, colours, minQuestionCount);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Options_Delete")]
		public int Quiz_Options_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Options_Update")]
		public int Quiz_Options_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuestionId", DbType="Int")] System.Nullable<int> questionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="NVarChar(MAX)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResourceId", DbType="Int")] System.Nullable<int> resourceId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Score", DbType="Decimal(18,1)")] System.Nullable<decimal> score)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, questionId, title, resourceId, score);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Questions_Delete")]
		public int Quiz_Questions_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Questions_Update")]
		public int Quiz_Questions_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SectionId", DbType="NVarChar(MAX)")] string sectionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="NVarChar(MAX)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Alias", DbType="NVarChar(MAX)")] string alias, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BinaryAnswer", DbType="Bit")] System.Nullable<bool> binaryAnswer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaxScore", DbType="Decimal(18,1)")] System.Nullable<decimal> maxScore, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MinScore", DbType="Decimal(18,1)")] System.Nullable<decimal> minScore)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, sectionId, title, alias, description, binaryAnswer, maxScore, minScore);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_RequiredResources_Delete")]
		public int Quiz_RequiredResources_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Resources_Update")]
		public int Quiz_Resources_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="NVarChar(MAX)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Url", DbType="NVarChar(MAX)")] string url, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ImageUrl", DbType="NVarChar(MAX)")] string imageUrl)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, title, description, url, imageUrl);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Sections_Delete")]
		public int Quiz_Sections_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Sections_Update")]
		public int Quiz_Sections_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="NVarChar(MAX)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MinQuestionCount", DbType="Int")] System.Nullable<int> minQuestionCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, title, description, minQuestionCount);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Sections_GetById")]
		public ISingleResult<Quiz_Sections_GetByIdResult> Quiz_Sections_GetById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<Quiz_Sections_GetByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Quiz_Resources_Delete")]
		public int Quiz_Resources_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class Quiz_Answers_GetByQuizIdResult
	{
		
		private int _Id;
		
		private int _QuizId;
		
		private string _Title;
		
		private string _Description;
		
		private System.Nullable<decimal> _MinScore;
		
		private System.Nullable<decimal> _MaxScore;
		
		public Quiz_Answers_GetByQuizIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizId", DbType="Int NOT NULL")]
		public int QuizId
		{
			get
			{
				return this._QuizId;
			}
			set
			{
				if ((this._QuizId != value))
				{
					this._QuizId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinScore", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> MinScore
		{
			get
			{
				return this._MinScore;
			}
			set
			{
				if ((this._MinScore != value))
				{
					this._MinScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxScore", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> MaxScore
		{
			get
			{
				return this._MaxScore;
			}
			set
			{
				if ((this._MaxScore != value))
				{
					this._MaxScore = value;
				}
			}
		}
	}
	
	public partial class Quiz_Sections_GetByQuizIdResult
	{
		
		private int _Id;
		
		private int _QuizId;
		
		private string _Title;
		
		private string _Description;
		
		private System.Nullable<int> _MinQuestionCount;
		
		public Quiz_Sections_GetByQuizIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizId", DbType="Int NOT NULL")]
		public int QuizId
		{
			get
			{
				return this._QuizId;
			}
			set
			{
				if ((this._QuizId != value))
				{
					this._QuizId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinQuestionCount", DbType="Int")]
		public System.Nullable<int> MinQuestionCount
		{
			get
			{
				return this._MinQuestionCount;
			}
			set
			{
				if ((this._MinQuestionCount != value))
				{
					this._MinQuestionCount = value;
				}
			}
		}
	}
	
	public partial class Quiz_Entries_GetByQuizIdResult
	{
		
		private int _Id;
		
		private int _QuizId;
		
		private decimal _Score;
		
		public Quiz_Entries_GetByQuizIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizId", DbType="Int NOT NULL")]
		public int QuizId
		{
			get
			{
				return this._QuizId;
			}
			set
			{
				if ((this._QuizId != value))
				{
					this._QuizId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Score", DbType="Decimal(18,1) NOT NULL")]
		public decimal Score
		{
			get
			{
				return this._Score;
			}
			set
			{
				if ((this._Score != value))
				{
					this._Score = value;
				}
			}
		}
	}
	
	public partial class Quiz_Results_GetByEntryIdResult
	{
		
		private int _Id;
		
		private int _EntryId;
		
		private int _OptionId;
		
		public Quiz_Results_GetByEntryIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryId", DbType="Int NOT NULL")]
		public int EntryId
		{
			get
			{
				return this._EntryId;
			}
			set
			{
				if ((this._EntryId != value))
				{
					this._EntryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionId", DbType="Int NOT NULL")]
		public int OptionId
		{
			get
			{
				return this._OptionId;
			}
			set
			{
				if ((this._OptionId != value))
				{
					this._OptionId = value;
				}
			}
		}
	}
	
	public partial class Quiz_Options_GetByIdResult
	{
		
		private int _Id;
		
		private int _QuizId;
		
		private int _QuestionId;
		
		private string _Title;
		
		private System.Nullable<int> _ResourceId;
		
		private System.Nullable<decimal> _Score;
		
		public Quiz_Options_GetByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizId", DbType="Int NOT NULL")]
		public int QuizId
		{
			get
			{
				return this._QuizId;
			}
			set
			{
				if ((this._QuizId != value))
				{
					this._QuizId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", DbType="Int NOT NULL")]
		public int QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					this._QuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceId", DbType="Int")]
		public System.Nullable<int> ResourceId
		{
			get
			{
				return this._ResourceId;
			}
			set
			{
				if ((this._ResourceId != value))
				{
					this._ResourceId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Score", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Score
		{
			get
			{
				return this._Score;
			}
			set
			{
				if ((this._Score != value))
				{
					this._Score = value;
				}
			}
		}
	}
	
	public partial class Quiz_Options_GetByQuestionIdResult
	{
		
		private int _Id;
		
		private int _QuizId;
		
		private int _QuestionId;
		
		private string _Title;
		
		private System.Nullable<int> _ResourceId;
		
		private System.Nullable<decimal> _Score;
		
		public Quiz_Options_GetByQuestionIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizId", DbType="Int NOT NULL")]
		public int QuizId
		{
			get
			{
				return this._QuizId;
			}
			set
			{
				if ((this._QuizId != value))
				{
					this._QuizId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", DbType="Int NOT NULL")]
		public int QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					this._QuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceId", DbType="Int")]
		public System.Nullable<int> ResourceId
		{
			get
			{
				return this._ResourceId;
			}
			set
			{
				if ((this._ResourceId != value))
				{
					this._ResourceId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Score", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Score
		{
			get
			{
				return this._Score;
			}
			set
			{
				if ((this._Score != value))
				{
					this._Score = value;
				}
			}
		}
	}
	
	public partial class Quiz_Questions_GetByQuizIdResult
	{
		
		private int _Id;
		
		private int _QuizId;
		
		private string _SectionId;
		
		private string _Title;
		
		private string _Alias;
		
		private string _Description;
		
		private bool _BinaryAnswer;
		
		private System.Nullable<decimal> _MaxScore;
		
		private System.Nullable<decimal> _MinScore;
		
		public Quiz_Questions_GetByQuizIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizId", DbType="Int NOT NULL")]
		public int QuizId
		{
			get
			{
				return this._QuizId;
			}
			set
			{
				if ((this._QuizId != value))
				{
					this._QuizId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionId", DbType="NVarChar(MAX)")]
		public string SectionId
		{
			get
			{
				return this._SectionId;
			}
			set
			{
				if ((this._SectionId != value))
				{
					this._SectionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias", DbType="NVarChar(MAX)")]
		public string Alias
		{
			get
			{
				return this._Alias;
			}
			set
			{
				if ((this._Alias != value))
				{
					this._Alias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BinaryAnswer", DbType="Bit NOT NULL")]
		public bool BinaryAnswer
		{
			get
			{
				return this._BinaryAnswer;
			}
			set
			{
				if ((this._BinaryAnswer != value))
				{
					this._BinaryAnswer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxScore", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> MaxScore
		{
			get
			{
				return this._MaxScore;
			}
			set
			{
				if ((this._MaxScore != value))
				{
					this._MaxScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinScore", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> MinScore
		{
			get
			{
				return this._MinScore;
			}
			set
			{
				if ((this._MinScore != value))
				{
					this._MinScore = value;
				}
			}
		}
	}
	
	public partial class Quiz_Questions_GetBySectionIdResult
	{
		
		private int _Id;
		
		private int _QuizId;
		
		private string _SectionId;
		
		private string _Title;
		
		private string _Alias;
		
		private string _Description;
		
		private bool _BinaryAnswer;
		
		private System.Nullable<decimal> _MaxScore;
		
		private System.Nullable<decimal> _MinScore;
		
		public Quiz_Questions_GetBySectionIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizId", DbType="Int NOT NULL")]
		public int QuizId
		{
			get
			{
				return this._QuizId;
			}
			set
			{
				if ((this._QuizId != value))
				{
					this._QuizId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionId", DbType="NVarChar(MAX)")]
		public string SectionId
		{
			get
			{
				return this._SectionId;
			}
			set
			{
				if ((this._SectionId != value))
				{
					this._SectionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias", DbType="NVarChar(MAX)")]
		public string Alias
		{
			get
			{
				return this._Alias;
			}
			set
			{
				if ((this._Alias != value))
				{
					this._Alias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BinaryAnswer", DbType="Bit NOT NULL")]
		public bool BinaryAnswer
		{
			get
			{
				return this._BinaryAnswer;
			}
			set
			{
				if ((this._BinaryAnswer != value))
				{
					this._BinaryAnswer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxScore", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> MaxScore
		{
			get
			{
				return this._MaxScore;
			}
			set
			{
				if ((this._MaxScore != value))
				{
					this._MaxScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinScore", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> MinScore
		{
			get
			{
				return this._MinScore;
			}
			set
			{
				if ((this._MinScore != value))
				{
					this._MinScore = value;
				}
			}
		}
	}
	
	public partial class Quiz_Questions_GetByIdResult
	{
		
		private int _Id;
		
		private int _QuizId;
		
		private string _SectionId;
		
		private string _Title;
		
		private string _Alias;
		
		private string _Description;
		
		private bool _BinaryAnswer;
		
		private System.Nullable<decimal> _MaxScore;
		
		private System.Nullable<decimal> _MinScore;
		
		public Quiz_Questions_GetByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizId", DbType="Int NOT NULL")]
		public int QuizId
		{
			get
			{
				return this._QuizId;
			}
			set
			{
				if ((this._QuizId != value))
				{
					this._QuizId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionId", DbType="NVarChar(MAX)")]
		public string SectionId
		{
			get
			{
				return this._SectionId;
			}
			set
			{
				if ((this._SectionId != value))
				{
					this._SectionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias", DbType="NVarChar(MAX)")]
		public string Alias
		{
			get
			{
				return this._Alias;
			}
			set
			{
				if ((this._Alias != value))
				{
					this._Alias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BinaryAnswer", DbType="Bit NOT NULL")]
		public bool BinaryAnswer
		{
			get
			{
				return this._BinaryAnswer;
			}
			set
			{
				if ((this._BinaryAnswer != value))
				{
					this._BinaryAnswer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxScore", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> MaxScore
		{
			get
			{
				return this._MaxScore;
			}
			set
			{
				if ((this._MaxScore != value))
				{
					this._MaxScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinScore", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> MinScore
		{
			get
			{
				return this._MinScore;
			}
			set
			{
				if ((this._MinScore != value))
				{
					this._MinScore = value;
				}
			}
		}
	}
	
	public partial class Quiz_Entries_InsertResult
	{
		
		private System.Nullable<decimal> _Id;
		
		public Quiz_Entries_InsertResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	
	public partial class Quiz_Results_InsertResult
	{
		
		private System.Nullable<decimal> _Id;
		
		public Quiz_Results_InsertResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	
	public partial class Quiz_GetAllResult
	{
		
		private int _Id;
		
		private string _Title;
		
		private string _Logo;
		
		private string _Description;
		
		private string _BackgroundImage;
		
		private string _Colours;
		
		private System.Nullable<int> _MinQuestionCount;
		
		private System.Nullable<int> _RequiredResourceId;
		
		public Quiz_GetAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo", DbType="NVarChar(MAX)")]
		public string Logo
		{
			get
			{
				return this._Logo;
			}
			set
			{
				if ((this._Logo != value))
				{
					this._Logo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackgroundImage", DbType="NVarChar(MAX)")]
		public string BackgroundImage
		{
			get
			{
				return this._BackgroundImage;
			}
			set
			{
				if ((this._BackgroundImage != value))
				{
					this._BackgroundImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Colours", DbType="NVarChar(MAX)")]
		public string Colours
		{
			get
			{
				return this._Colours;
			}
			set
			{
				if ((this._Colours != value))
				{
					this._Colours = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinQuestionCount", DbType="Int")]
		public System.Nullable<int> MinQuestionCount
		{
			get
			{
				return this._MinQuestionCount;
			}
			set
			{
				if ((this._MinQuestionCount != value))
				{
					this._MinQuestionCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequiredResourceId", DbType="Int")]
		public System.Nullable<int> RequiredResourceId
		{
			get
			{
				return this._RequiredResourceId;
			}
			set
			{
				if ((this._RequiredResourceId != value))
				{
					this._RequiredResourceId = value;
				}
			}
		}
	}
	
	public partial class Quiz_GetByIdResult
	{
		
		private int _Id;
		
		private string _Title;
		
		private string _Logo;
		
		private string _Description;
		
		private string _BackgroundImage;
		
		private string _Colours;
		
		private System.Nullable<int> _MinQuestionCount;
		
		private System.Nullable<int> _RequiredResourceId;
		
		public Quiz_GetByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo", DbType="NVarChar(MAX)")]
		public string Logo
		{
			get
			{
				return this._Logo;
			}
			set
			{
				if ((this._Logo != value))
				{
					this._Logo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackgroundImage", DbType="NVarChar(MAX)")]
		public string BackgroundImage
		{
			get
			{
				return this._BackgroundImage;
			}
			set
			{
				if ((this._BackgroundImage != value))
				{
					this._BackgroundImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Colours", DbType="NVarChar(MAX)")]
		public string Colours
		{
			get
			{
				return this._Colours;
			}
			set
			{
				if ((this._Colours != value))
				{
					this._Colours = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinQuestionCount", DbType="Int")]
		public System.Nullable<int> MinQuestionCount
		{
			get
			{
				return this._MinQuestionCount;
			}
			set
			{
				if ((this._MinQuestionCount != value))
				{
					this._MinQuestionCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequiredResourceId", DbType="Int")]
		public System.Nullable<int> RequiredResourceId
		{
			get
			{
				return this._RequiredResourceId;
			}
			set
			{
				if ((this._RequiredResourceId != value))
				{
					this._RequiredResourceId = value;
				}
			}
		}
	}
	
	public partial class Quiz_Resources_GetByIdResult
	{
		
		private int _Id;
		
		private string _Title;
		
		private string _Url;
		
		private string _Description;
		
		private string _ImageUrl;
		
		public Quiz_Resources_GetByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(MAX)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this._Url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageUrl", DbType="NVarChar(MAX)")]
		public string ImageUrl
		{
			get
			{
				return this._ImageUrl;
			}
			set
			{
				if ((this._ImageUrl != value))
				{
					this._ImageUrl = value;
				}
			}
		}
	}
	
	public partial class Quiz_RequiredResources_GetByQuizIdResult
	{
		
		private int _Id;
		
		private int _QuizId;
		
		private int _ResourceId;
		
		public Quiz_RequiredResources_GetByQuizIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizId", DbType="Int NOT NULL")]
		public int QuizId
		{
			get
			{
				return this._QuizId;
			}
			set
			{
				if ((this._QuizId != value))
				{
					this._QuizId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceId", DbType="Int NOT NULL")]
		public int ResourceId
		{
			get
			{
				return this._ResourceId;
			}
			set
			{
				if ((this._ResourceId != value))
				{
					this._ResourceId = value;
				}
			}
		}
	}
	
	public partial class Quiz_InsertResult
	{
		
		private System.Nullable<int> _Id;
		
		public Quiz_InsertResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int")]
		public System.Nullable<int> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	
	public partial class Quiz_Resources_InsertResult
	{
		
		private System.Nullable<int> _Id;
		
		public Quiz_Resources_InsertResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int")]
		public System.Nullable<int> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	
	public partial class Quiz_Sections_InsertResult
	{
		
		private System.Nullable<int> _Id;
		
		public Quiz_Sections_InsertResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int")]
		public System.Nullable<int> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	
	public partial class Quiz_Questions_InsertResult
	{
		
		private System.Nullable<int> _Id;
		
		public Quiz_Questions_InsertResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int")]
		public System.Nullable<int> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	
	public partial class Quiz_Sections_GetByIdResult
	{
		
		private int _Id;
		
		private int _QuizId;
		
		private string _Title;
		
		private string _Description;
		
		private System.Nullable<int> _MinQuestionCount;
		
		public Quiz_Sections_GetByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizId", DbType="Int NOT NULL")]
		public int QuizId
		{
			get
			{
				return this._QuizId;
			}
			set
			{
				if ((this._QuizId != value))
				{
					this._QuizId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinQuestionCount", DbType="Int")]
		public System.Nullable<int> MinQuestionCount
		{
			get
			{
				return this._MinQuestionCount;
			}
			set
			{
				if ((this._MinQuestionCount != value))
				{
					this._MinQuestionCount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
